# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.6 on 2021-08-02 20:32

from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BitbucketAppInstall",
            fields=[
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("last_updated", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow)),
                (
                    "_app_state",
                    models.CharField(
                        choices=[("installed", "INSTALLED"), ("uninstalled", "UNINSTALLED")],
                        db_column="app_state",
                        db_index=True,
                        default="installed",
                        max_length=15,
                    ),
                ),
                ("customer_id", models.CharField(max_length=22)),
                ("client_key", models.CharField(max_length=128)),
                ("shared_secret", models.CharField(max_length=128)),
                ("account_name", models.CharField(max_length=64)),
                (
                    "account_id",
                    models.CharField(db_index=True, editable=False, max_length=64, primary_key=True, serialize=False),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
