# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.12 on 2022-02-11 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("oss_metrics", "0002_upsertgithubrepostatsforday"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleUpsertGithubRepoStats",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("customer_id", models.CharField(editable=False, max_length=22)),
                ("repo_id", models.CharField(editable=False, max_length=22, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
