# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.2 on 2022-02-15 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("oss_metrics", "0003_scheduleupsertgithubrepostats"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScheduleAnonymouseTelemetryProcessing",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("period_minutes", models.IntegerField(null=True)),
                ("journal_id", models.CharField(editable=False, max_length=36, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
