# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.1 on 2019-06-05 21:42

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    initial = True

    dependencies = [("webresource", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="License",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, db_index=True, max_length=300)),
                ("url", models.URLField(blank=True, db_index=True, max_length=500)),
                (
                    "distribution",
                    models.CharField(blank=True, choices=[("repo", "repo"), ("manual", "manual")], max_length=20),
                ),
            ],
            options={"unique_together": {("name", "url", "distribution")}},
        ),
        migrations.CreateModel(
            name="MavenArtifact",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("group_id", models.CharField(max_length=150)),
                ("artifact_id", models.CharField(max_length=150)),
            ],
            options={"unique_together": {("group_id", "artifact_id")}},
        ),
        migrations.CreateModel(
            name="MavenArtifactVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=150)),
                ("url", models.URLField(blank=True, max_length=1024)),
                ("scm_url", models.URLField(blank=True, max_length=1024)),
                ("packaging", models.CharField(blank=True, max_length=30)),
                ("completed_at", models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc))),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mavenartifactversions",
                        to="packagerepomaven.MavenArtifact",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="MavenMetadata",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "web_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="maven_metadata",
                        to="webresource.WebResource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="POM",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=150)),
                (
                    "artifact",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poms",
                        to="packagerepomaven.MavenArtifact",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="packagerepomaven.POM",
                    ),
                ),
                (
                    "web_resource",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="pom", to="webresource.WebResource"
                    ),
                ),
            ],
            options={"abstract": False, "unique_together": {("artifact", "version")}},
        ),
        migrations.CreateModel(
            name="POMArtifactVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "artifact_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pom_refs",
                        to="packagerepomaven.MavenArtifactVersion",
                    ),
                ),
                (
                    "pom",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="artifact_version_ref",
                        to="packagerepomaven.POM",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Organization",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, db_index=True, default="", max_length=150)),
                ("url", models.URLField(blank=True, db_index=True, default="", max_length=500)),
            ],
            options={"unique_together": {("name", "url")}},
        ),
        migrations.CreateModel(
            name="MavenStats",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope", models.CharField(blank=True, db_index=True, max_length=200)),
                ("shard", models.IntegerField()),
                ("num_artifacts", models.IntegerField(default=0)),
                ("num_versions", models.IntegerField(default=0)),
                ("num_poms", models.IntegerField(default=0)),
                ("num_binary_jars", models.IntegerField(default=0)),
                ("num_source_jars", models.IntegerField(default=0)),
                ("num_javadoc_jars", models.IntegerField(default=0)),
            ],
            options={"unique_together": {("scope", "shard")}},
        ),
        migrations.CreateModel(
            name="MavenMetadataVersion",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "artifact_version",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="packagerepomaven.MavenArtifactVersion"
                    ),
                ),
                (
                    "maven_metadata",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="packagerepomaven.MavenMetadata",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MavenDependency",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("depends_on_version_spec", models.CharField(max_length=200)),
                ("classifier", models.CharField(blank=True, max_length=50)),
                ("type", models.CharField(blank=True, max_length=50)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("compile", "compile"),
                            ("provided", "provided"),
                            ("runtime", "runtime"),
                            ("test", "test"),
                            ("system", "system"),
                        ],
                        default="compile",
                        max_length=8,
                    ),
                ),
                ("optional", models.BooleanField(default=False)),
                (
                    "dependent",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="packagerepomaven.MavenArtifactVersion"
                    ),
                ),
                (
                    "depends_on_artifact",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packagerepomaven.MavenArtifact"),
                ),
            ],
            options={"unique_together": {("dependent", "depends_on_artifact", "classifier")}},
        ),
        migrations.AddField(
            model_name="mavenartifactversion",
            name="direct_declared_dependencies",
            field=models.ManyToManyField(
                blank=True, through="packagerepomaven.MavenDependency", to="packagerepomaven.MavenArtifact"
            ),
        ),
        migrations.AddField(
            model_name="mavenartifactversion",
            name="licenses",
            field=models.ManyToManyField(to="packagerepomaven.License"),
        ),
        migrations.AddField(
            model_name="mavenartifactversion",
            name="organization",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="packagerepomaven.Organization"
            ),
        ),
        migrations.AlterUniqueTogether(name="mavenartifactversion", unique_together={("artifact", "version")}),
    ]
