# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.2 on 2020-01-10 01:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("workflow", "0005_auto_20191115_1958")]

    operations = [
        migrations.CreateModel(
            name="PeriodicallyCheckAccessTokens",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("period_minutes", models.IntegerField(null=True)),
            ],
            options={"abstract": False},
        )
    ]
