# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.1 on 2020-09-15 23:42

import shortuuid
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_periodicallyrevoketokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="RestrictedAccessToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.uuid, editable=False, max_length=22, primary_key=True, serialize=False
                    ),
                ),
                ("repo_id", models.CharField(db_index=True, editable=False, max_length=22)),
                ("issued_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("ci_build_key", models.CharField(db_index=True, editable=False, max_length=22)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
