# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.3 on 2020-11-14 00:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_restrictedaccesstoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="restrictedaccesstoken",
            name="ci_build_key",
            field=models.CharField(db_index=True, editable=False, max_length=48),
        ),
    ]
