# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_auto_20201114_0010"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubRepoConfig",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("repo_id", models.CharField(db_index=True, editable=False, max_length=22)),
                ("max_build_tokens", models.IntegerField(default=3)),
                ("started_treshold_sec", models.IntegerField(default=360)),
                ("token_ttl_sec", models.IntegerField(default=180)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
