# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_githubrepoconfig"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubrepoconfig",
            name="repo_id",
            field=models.CharField(db_index=True, max_length=22),
        ),
    ]
