# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-11 00:16

import shortuuid.main
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_auto_20201207_2141"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccessTokenExchangeCode",
            fields=[
                ("user_api_id", models.CharField(editable=False, max_length=22)),
                ("repo_id", models.CharField(editable=False, max_length=22)),
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                (
                    "code",
                    models.CharField(
                        default=shortuuid.main.ShortUUID.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                (
                    "_code_state",
                    models.CharField(
                        choices=[
                            ("available", "AVAILABLE"),
                            ("expired", "EXPIRED"),
                            ("used", "USED"),
                            ("overridden", "OVERRIDDEN"),
                        ],
                        db_column="state",
                        default="available",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name": "JWT Exchange code",
                "verbose_name_plural": "JWT Exchange codes",
            },
        ),
    ]
