# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-14 16:12

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_auto_20201212_0003"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAccessConfig",
            fields=[
                ("user_api_id", models.CharField(max_length=22, primary_key=True, serialize=False, unique=True)),
                ("_allowed_audiences", models.CharField(max_length=250)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="code",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
