# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-25 23:40

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_auto_20210104_1914"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="code",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="allowlistsignup",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="githubrepoconfig",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
