# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-29 02:02

import shortuuid.main
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_auto_20210326_2127"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="code",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="UserAuth",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("user_api_id", models.CharField(db_index=True, max_length=22)),
                (
                    "_provider",
                    models.CharField(
                        choices=[("github", "GITHUB"), ("bitbucket", "BITBUCKET")],
                        db_column="provider",
                        db_index=True,
                        editable=False,
                        max_length=10,
                    ),
                ),
                ("user_id", models.CharField(db_index=True, editable=False, max_length=48)),
                ("created", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                ("_email_addresses", models.CharField(max_length=256)),
            ],
            options={
                "unique_together": {("user_id", "_provider")},
            },
        ),
    ]
