# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-31 19:43

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_auto_20210329_0202"),
    ]

    operations = [
        migrations.AddField(
            model_name="userauth",
            name="username",
            field=models.CharField(db_index=True, default="", max_length=150),
        ),
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="code",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
