# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.8 on 2021-04-06 23:35

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_auto_20210406_2212"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="code",
            field=models.CharField(
                default=shortuuid.main.ShortUUID.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="UserCustomerAccessConfig",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_api_id", models.CharField(editable=False, max_length=22)),
                ("customer_id", models.CharField(editable=False, max_length=22)),
                ("_allowed_audiences", models.CharField(max_length=250)),
            ],
            options={
                "unique_together": {("user_api_id", "customer_id")},
            },
        ),
    ]
