# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.8 on 2021-04-07 20:05

import shortuuid.main
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0016_auto_20210406_2335"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="code",
            field=models.CharField(
                default=shortuuid.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="usercustomeraccessconfig",
            name="customer_id",
            field=models.CharField(max_length=22),
        ),
        migrations.AlterField(
            model_name="usercustomeraccessconfig",
            name="user_api_id",
            field=models.CharField(max_length=22),
        ),
    ]
