# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.4 on 2021-06-03 21:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0021_auto_20210601_2159"),
    ]

    operations = [
        migrations.AddField(
            model_name="allowlistsignup",
            name="default_customer_slug",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
    ]
