# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.4 on 2021-06-15 15:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0022_allowlistsignup_default_customer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="impersonationauditlog",
            name="session_id",
            field=models.ForeignKey(
                db_column="session_id",
                editable=False,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.impersonationsession",
            ),
        ),
    ]
