# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.10 on 2021-12-28 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("users", "0023_alter_impersonationauditlog_session_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicallyExportCustomers",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("period_minutes", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
