# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.3 on 2022-04-05 18:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("users", "0024_periodicallyexportcustomers"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicallyNotifyExpringTokens",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("period_minutes", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
