# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.4 on 2022-04-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_periodicallynotifyexpringtokens"),
    ]

    operations = [
        migrations.AddField(
            model_name="usercustomeraccessconfig",
            name="_role",
            field=models.CharField(  # noqa: DJ01
                choices=[("org_admin", "ORG_ADMIN"), ("user", "USER")],
                db_column="role",
                default="user",
                max_length=15,
                null=True,
            ),
        ),
    ]
