# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.5 on 2022-06-03 17:43

from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_usercustomeraccessconfig__role"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTermsOfServiceAcceptance",
            fields=[
                ("id", models.AutoField(editable=False, primary_key=True, serialize=False)),
                ("user_api_id", models.CharField(db_index=True, editable=False, max_length=22)),
                ("created", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("tos_version", models.CharField(db_index=True, editable=False, max_length=32)),
                ("email", models.EmailField(editable=False, max_length=254)),
                ("client_ip", models.GenericIPAddressField(editable=False)),
                ("request_id", models.CharField(editable=False, max_length=40)),
            ],
            options={
                "unique_together": {("user_api_id", "tos_version")},
            },
        ),
    ]
