# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.2 on 2022-10-17 16:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0027_usertermsofserviceacceptance"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AllowListSignup",
        ),
    ]
