# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.3 on 2022-11-23 18:47

import shortuuid
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0028_delete_allowlistsignup"),
    ]

    operations = [
        migrations.CreateModel(
            name="RemoteExecWorkerToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("token", models.CharField(db_index=True, editable=False, max_length=64, unique=True)),
                ("customer_id", models.CharField(db_index=True, editable=False, max_length=22)),
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("description", models.CharField(max_length=256)),
                (
                    "_token_state",
                    models.CharField(
                        choices=[("active", "ACTIVE"), ("inactive", "INACTIVE")],
                        db_column="state",
                        default="active",
                        max_length=10,
                    ),
                ),
                ("user_api_id", models.CharField(db_index=True, editable=False, max_length=22)),
                ("customer_slug", models.CharField(max_length=64)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
