# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.3 on 2022-12-06 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_remoteexecworkertoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="remoteexecworkertoken",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
