# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

pex_binary(
    name="init_prod_db",
    entry_point="init_prod_db.py",
)
