# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.1 on 2019-06-05 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="WebResource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("url", models.URLField(db_index=True, max_length=500)),
                ("sha256_hexdigest", models.CharField(db_index=True, max_length=64)),
                ("freshness", models.DateTimeField(null=True)),
                ("encoding", models.CharField(blank=True, max_length=20)),
                ("etag", models.CharField(default="Not Set", max_length=100)),
                ("content_url", models.CharField(blank=True, max_length=1024)),
                ("content", models.BinaryField(null=True)),
                ("compression", models.CharField(choices=[("gz", "gzip"), ("id", "identity")], max_length=2)),
            ],
            options={"get_latest_by": "freshness"},
        ),
        migrations.CreateModel(
            name="WebResourceLink",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("target", models.URLField(db_index=True, max_length=500)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links_from",
                        to="webresource.WebResource",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="webresource", index=models.Index(fields=["url", "freshness"], name="webresource_url_28a3e2_idx")
        ),
        migrations.AlterUniqueTogether(name="webresource", unique_together={("url", "sha256_hexdigest")}),
        migrations.AlterUniqueTogether(name="webresourcelink", unique_together={("source", "target")}),
    ]
