# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("webresource", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="webresource",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="webresourcelink",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
