# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

python_tests(name="tests")

pex_binary(name="setup_ui_jwt", entry_point="setup_ui_jwt.py")

pex_binary(name="setup_jwt_keys", entry_point="setup_jwt_keys.py")
