#!/usr/bin/env bash
# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

set -euo pipefail

cd "$(git rev-parse --show-toplevel)"

VENV=$(mktemp -d -t pants_ci_lockfile_venv.XXXXX)
python3 -m venv "${VENV}"

"${VENV}/bin/pip" install --upgrade "pip>=23.0" "pip-tools==6.12.2"
requirements_file=prod/docker/ci/requirements.txt
"${VENV}/bin/pip-compile" --no-header --generate-hashes --allow-unsafe --output-file "${requirements_file}" prod/docker/ci/pants-reqs.in

sed -i .old "1s|^|# Generated by prod/docker/ci/update-pants-reqs.sh on $(date)\\n|" "${requirements_file}"
rm "${requirements_file}.old"