# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

python_tests(name="tests")

pex_binary(
    name="iam_keys_watcher",
    entry_point="check_iam_access_keys.py",
)
