# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-15 22:31

import django.contrib.postgres.fields
import django.contrib.postgres.fields.jsonb
import django.contrib.postgres.indexes
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("webresource", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="Distribution",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("filename", models.CharField(max_length=300, unique=True)),
                ("url", models.URLField(max_length=500, unique=True)),
                (
                    "dist_type",
                    models.CharField(
                        choices=[("WHEEL", "WHEEL"), ("BDIST", "BDIST"), ("SDIST", "SDIST")], max_length=20
                    ),
                ),
                ("serial_from", models.IntegerField(db_index=True)),
                ("serial_to", models.IntegerField(db_index=True, null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(db_index=True, max_length=100, unique=True)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Snapshot",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("project_map", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="Release",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("version", models.CharField(max_length=100)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="releases",
                        to="packagerepopypi.Project",
                    ),
                ),
            ],
            options={"unique_together": {("project", "version")}},
        ),
        migrations.CreateModel(
            name="DistributionData",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("metadata", django.contrib.postgres.fields.jsonb.JSONField()),
                (
                    "modules",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), size=None),
                ),
                (
                    "distribution",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="data",
                        to="packagerepopypi.Distribution",
                    ),
                ),
                (
                    "web_resource",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="webresource.WebResource"),
                ),
            ],
        ),
        migrations.AddField(
            model_name="distribution",
            name="release",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="distributions", to="packagerepopypi.Release"
            ),
        ),
        migrations.AddIndex(
            model_name="distributiondata",
            index=django.contrib.postgres.indexes.GinIndex(fields=["metadata"], name="packagerepo_metadat_68c1f3_gin"),
        ),
        migrations.AddIndex(
            model_name="distributiondata",
            index=django.contrib.postgres.indexes.GinIndex(fields=["modules"], name="packagerepo_modules_9c8371_gin"),
        ),
    ]
