# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.5 on 2019-10-18 19:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("packagerepopypi", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="dist_type",
            field=models.CharField(
                choices=[
                    ("WHEEL", "WHEEL"),
                    ("BDIST", "BDIST"),
                    ("SDIST", "SDIST"),
                    ("EXE", "EXE"),
                    ("RPM", "RPM"),
                    ("DUMB", "DUMB"),
                    ("MSI", "MSI"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="distribution",
            name="filename",
            field=models.CharField(db_index=True, max_length=300, unique=True),
        ),
    ]
