# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.5 on 2019-11-12 18:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("packagerepopypi", "0002_auto_20191018_1916")]

    operations = [migrations.DeleteModel(name="Snapshot")]
