# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1 on 2020-08-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagerepopypi", "0003_delete_snapshot"),
    ]

    operations = [
        migrations.AlterField(model_name="distributiondata", name="metadata", field=models.JSONField()),
    ]
