# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagerepopypi", "0004_auto_20200817_2202"),
    ]

    operations = [
        migrations.AlterField(
            model_name="distribution",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="distributiondata",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="project",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="release",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
