# Copyright 2018 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.6 on 2021-08-18 16:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("packagerepopypi", "0005_auto_20210315_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="name",
            field=models.CharField(db_index=True, max_length=256, unique=True),
        ),
    ]
