# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.4 on 2022-05-12 21:46

import django.db.models.deletion
import shortuuid
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailMessageRequest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("topic_name", models.CharField(max_length=64)),
                ("recipient_user_api_id", models.CharField(max_length=22)),
                ("message_key", models.CharField(max_length=256)),
                ("context_data", models.JSONField()),
                (
                    "_status",
                    models.CharField(
                        choices=[
                            ("QUEUED", "QUEUED"),
                            ("DUPLICATE", "DUPLICATE"),
                            ("USER_NA", "USER_NA"),
                            ("SENDING", "SENDING"),
                        ],
                        db_column="status",
                        default="QUEUED",
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ProcessEmailMessageRequest",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("requested_message_id", models.CharField(editable=False, max_length=22, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SentEmailMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("to", models.EmailField(max_length=254)),
                ("recipient_user_api_id", models.CharField(max_length=22)),
                ("subject", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow)),
                ("rendered_email_s3_url", models.CharField(max_length=512)),
                (
                    "_status",
                    models.CharField(
                        choices=[
                            ("PRE_SEND", "PRE_SEND"),
                            ("IN_FLIGHT", "IN_FLIGHT"),
                            ("FAILED", "FAILED"),
                            ("COMPLETE", "COMPLETE"),
                        ],
                        db_column="status",
                        default="IN_FLIGHT",
                        max_length=16,
                    ),
                ),
                (
                    "_provider",
                    models.CharField(
                        choices=[("ses", "AWS_SES"), ("sendgrid", "SENDGRID")],
                        db_column="provider",
                        default="ses",
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(default="", max_length=64)),
                ("failure_reason", models.CharField(default="", max_length=256)),
                (
                    "requested_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="email_notifications.emailmessagerequest"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
