# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.3 on 2019-07-12 15:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("site", "0001_initial")]

    operations = [
        migrations.AddConstraint(
            model_name="customeruser",
            constraint=models.UniqueConstraint(fields=("customer", "user"), name="unique_customeruser"),
        )
    ]
