# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.5 on 2019-11-14 21:40

import shortuuid
from django.db import migrations, models

import toolchain.django.site.utils.validators


class Migration(migrations.Migration):
    dependencies = [("site", "0002_auto_20190712_1555")]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="slug",
            field=models.CharField(
                default="dummy",
                max_length=64,
                validators=[
                    toolchain.django.site.utils.validators.validate_noslash,
                    toolchain.django.site.utils.validators.validate_nopipe,
                ],
            ),
        ),
        migrations.AddField(
            model_name="repo",
            name="slug",
            field=models.CharField(
                default="dummy",
                max_length=64,
                validators=[
                    toolchain.django.site.utils.validators.validate_noslash,
                    toolchain.django.site.utils.validators.validate_nopipe,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="id",
            field=models.CharField(
                db_index=True,
                default=shortuuid.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="id",
            field=models.CharField(
                db_index=True,
                default=shortuuid.uuid,
                editable=False,
                max_length=22,
                primary_key=True,
                serialize=False,
                unique=True,
            ),
        ),
    ]
