# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.5 on 2019-11-15 00:42

from django.db import migrations, models

import toolchain.django.site.utils.validators


class Migration(migrations.Migration):
    dependencies = [("site", "0003_auto_20191114_2140")]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="slug",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    toolchain.django.site.utils.validators.validate_noslash,
                    toolchain.django.site.utils.validators.validate_nopipe,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="repo",
            name="slug",
            field=models.CharField(
                max_length=64,
                unique=True,
                validators=[
                    toolchain.django.site.utils.validators.validate_noslash,
                    toolchain.django.site.utils.validators.validate_nopipe,
                ],
            ),
        ),
    ]
