# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.8 on 2019-12-05 01:55

import shortuuid
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [("site", "0004_auto_20191115_0042")]

    operations = [
        migrations.CreateModel(
            name="AccessTokenExchangeCode",
            fields=[
                ("user_api_id", models.CharField(max_length=22)),
                ("repo_id", models.CharField(max_length=22)),
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow)),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        default=shortuuid.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("_code_state", models.CharField(db_column="state", default="available", max_length=10)),
            ],
            options={"abstract": False},
        )
    ]
