# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.8 on 2019-12-16 23:24

import shortuuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("site", "0005_accesstokenexchangecode")]

    operations = [
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="code",
            field=models.CharField(
                default=shortuuid.uuid, editable=False, max_length=22, primary_key=True, serialize=False, unique=True
            ),
        )
    ]
