# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.8 on 2019-12-18 01:14

from django.db import migrations, models

from toolchain.base.datetime_tools import utcnow


class Migration(migrations.Migration):
    dependencies = [("site", "0006_auto_20191216_2324")]

    operations = [
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="created_at",
            field=models.DateTimeField(default=utcnow, editable=False),
        ),
        migrations.AlterField(
            model_name="accesstokenexchangecode", name="repo_id", field=models.CharField(editable=False, max_length=22)
        ),
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="user_api_id",
            field=models.CharField(editable=False, max_length=22),
        ),
    ]
