# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.8 on 2019-12-18 21:50

import shortuuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("site", "0007_auto_20191218_0114")]

    operations = [
        migrations.CreateModel(
            name="AllocatedAccessToken",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=shortuuid.uuid, editable=False, max_length=22, primary_key=True, serialize=False
                    ),
                ),
                ("user_api_id", models.CharField(db_index=True, editable=False, max_length=22)),
                ("expires_at", models.DateTimeField(db_index=True, editable=False)),
                (
                    "_token_state",
                    models.CharField(db_column="token_state", db_index=True, default="active", max_length=10),
                ),
                ("issued_at", models.DateTimeField(editable=False)),
                ("last_seen", models.DateTimeField(null=True)),
            ],
            options={"abstract": False},
        )
    ]
