# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.8 on 2019-12-27 19:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("site", "0008_allocatedaccesstoken")]

    operations = [
        migrations.AlterModelOptions(
            name="accesstokenexchangecode",
            options={"verbose_name": "JWT Exchange code", "verbose_name_plural": "JWT Exchange codes"},
        )
    ]
