# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.2 on 2020-01-24 02:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("site", "0009_auto_20191227_1955")]

    operations = [
        migrations.AlterField(
            model_name="toolchainuserdetails", name="avatar_url", field=models.URLField(blank=True, default="")
        ),
        migrations.AlterField(
            model_name="toolchainuserdetails", name="github_homepage", field=models.URLField(blank=True, default="")
        ),
        migrations.AlterField(
            model_name="whitelistedsignup", name="notes", field=models.CharField(blank=True, default="", max_length=256)
        ),
    ]
