# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.5 on 2020-04-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0010_auto_20200124_0232"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="_customer_state",
            field=models.CharField(db_column="state", default="active", max_length=10),
        ),
    ]
