# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.5 on 2020-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0011_customer__customer_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolchainuserdetails",
            name="github_user_id",
            field=models.CharField(db_index=True, default="", editable=False, max_length=8),
        ),
    ]
