# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.5 on 2020-04-14 00:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0012_toolchainuserdetails_github_user_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolchainuserdetails",
            name="github_user_id",
            field=models.CharField(db_index=True, editable=False, max_length=8, unique=True),
        ),
    ]
