# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.5 on 2020-04-16 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0013_auto_20200414_0047"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolchainuserdetails",
            name="github_username",
            field=models.CharField(default="", max_length=150),
        ),
    ]
