# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.5 on 2020-04-22 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0014_toolchainuserdetails_github_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocatedaccesstoken",
            name="_usage",
            field=models.CharField(db_column="usage", default="api", max_length=6),
        ),
    ]
