# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.3 on 2020-11-30 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0015_allocatedaccesstoken__usage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="toolchainuser",
            name="first_name",
            field=models.CharField(blank=True, max_length=150, verbose_name="first name"),
        ),
    ]
