# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.3 on 2020-11-30 19:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0016_auto_20201130_1618"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="_access_mode",
            field=models.CharField(db_column="access_mode", default="allow", max_length=10),
        ),
    ]
