# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-02 00:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0017_customer__access_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="_access_mode",
            field=models.CharField(
                choices=[("allow", "ALLOW_ACCESS"), ("other", "REQUIRE_OTHER")],
                db_column="access_mode",
                default="allow",
                max_length=10,
                verbose_name="Access mode",
            ),
        ),
    ]
