# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-03 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0018_auto_20201202_0026"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accesstokenexchangecode",
            name="_code_state",
            field=models.CharField(
                choices=[
                    ("available", "AVAILABLE"),
                    ("expired", "EXPIRED"),
                    ("used", "USED"),
                    ("overridden", "OVERRIDDEN"),
                ],
                db_column="state",
                default="available",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="allocatedaccesstoken",
            name="_token_state",
            field=models.CharField(
                choices=[("active", "ACTIVE"), ("expired", "EXPIRED"), ("revoked", "REVOKED")],
                db_column="token_state",
                db_index=True,
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="allocatedaccesstoken",
            name="_usage",
            field=models.CharField(
                choices=[("api", "API"), ("ui", "UI")], db_column="usage", default="api", max_length=6
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="_customer_state",
            field=models.CharField(
                choices=[("active", "ACTIVE"), ("inactive", "INACTIVE")],
                db_column="state",
                default="active",
                max_length=10,
            ),
        ),
    ]
