# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-04 16:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0019_auto_20201203_2030"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="_repo_state",
            field=models.CharField(
                choices=[("active", "ACTIVE"), ("inactive", "INACTIVE")],
                db_column="state",
                default="active",
                max_length=10,
            ),
        ),
    ]
