# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-07 20:37

from django.db import migrations, models

import toolchain.django.site.utils.validators


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0020_repo__repo_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="repo",
            name="slug",
            field=models.CharField(
                max_length=64,
                validators=[
                    toolchain.django.site.utils.validators.validate_noslash,
                    toolchain.django.site.utils.validators.validate_nopipe,
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="repo",
            constraint=models.UniqueConstraint(fields=("customer", "slug"), name="unique_customer_repo_slug"),
        ),
    ]
