# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-15 18:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0021_auto_20201207_2037"),
    ]

    operations = [
        migrations.DeleteModel(
            name="AccessTokenExchangeCode",
        ),
        migrations.DeleteModel(
            name="WhitelistedSignup",
        ),
    ]
