# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.5 on 2021-01-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0022_auto_20201215_1847"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolchainuser",
            name="email_was_verified",
        ),
        migrations.AddField(
            model_name="toolchainuser",
            name="full_name",
            field=models.CharField(blank=True, default="", max_length=150, verbose_name="full name"),
        ),
    ]
