# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.5 on 2021-01-21 17:49


from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0023_auto_20210120_2221"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolchainuser",
            name="email_was_verified",
            field=models.BooleanField(default=False),
        ),
    ]
