# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.5 on 2021-01-21 19:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0024_toolchainuser_email_was_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolchainuser",
            name="email_was_verified",
        ),
    ]
