# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.5 on 2021-01-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0025_remove_toolchainuser_email_was_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="logo_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
