# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0028_auto_20210325_2339"),
    ]

    operations = [
        migrations.AddField(
            model_name="toolchainuser",
            name="avatar_url",
            field=models.URLField(blank=True, default=""),
        ),
    ]
