# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-31 23:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0029_toolchainuser_avatar_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="_scm_provider",
            field=models.CharField(
                choices=[("github", "GITHUB"), ("bitbucket", "BITBUCKET")],
                db_column="scm_provider",
                default="github",
                max_length=10,
                verbose_name="SCM Provider",
            ),
        ),
    ]
