# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.8 on 2021-04-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0030_customer__scm_provider"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocatedaccesstoken",
            name="description",
            field=models.CharField(default="NA", max_length=256),
        ),
    ]
