# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.8 on 2021-04-16 20:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0031_allocatedaccesstoken_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocatedaccesstoken",
            name="description",
            field=models.CharField(default="NA", max_length=256, null=True),  # noqa: DJ01
        ),
    ]
