# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2 on 2021-04-28 16:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0032_auto_20210416_2019"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ToolchainUserDetails",
        ),
    ]
