# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.3 on 2021-05-19 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0033_delete_toolchainuserdetails"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="_customer_type",
            field=models.CharField(
                choices=[
                    ("customer", "CUSTOMER"),
                    ("internal", "INTERNAL"),
                    ("opensource", "OPEN_SOURCE"),
                    ("prospect", "PROSPECT"),
                ],
                db_column="type",
                default="prospect",
                max_length=10,
            ),
        ),
    ]
