# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.4 on 2021-06-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0034_customer__customer_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="allocatedaccesstoken",
            name="_audiences",
            field=models.CharField(  # noqa: DJ01
                db_column="audiences", default="", editable=False, max_length=250, null=True
            ),
        ),
        migrations.AddField(
            model_name="allocatedaccesstoken",
            name="repo_id",
            field=models.CharField(default="", editable=False, max_length=22, null=True),  # noqa: DJ01
        ),
        migrations.AlterField(
            model_name="allocatedaccesstoken",
            name="_usage",
            field=models.CharField(
                choices=[("api", "API"), ("ui", "UI")], db_column="usage", default="api", editable=False, max_length=6
            ),
        ),
    ]
