# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.6 on 2021-08-24 21:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0035_auto_20210608_1925"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="allocatedaccesstoken",
            table="site_allocatedaccesstoken",
        ),
    ]
