# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.6 on 2021-08-24 22:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0036_alter_allocatedaccesstoken_table"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AllocatedAccessToken",
            new_name="AllocatedRefreshToken",
        ),
    ]
