# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.9 on 2021-11-08 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0037_rename_allocatedaccesstoken_allocatedrefreshtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="repo",
            name="_visibility",
            field=models.CharField(
                choices=[("public", "PUBLIC"), ("private", "PRIVATE")],
                db_column="visibility",
                default="private",
                max_length=10,
            ),
        ),
    ]
