# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.4 on 2022-04-20 21:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0038_repo__visibility"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allocatedrefreshtoken",
            name="description",
            field=models.CharField(default="NA", max_length=256),
        ),
    ]
