# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.4 on 2022-05-18 16:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0039_alter_allocatedrefreshtoken_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="_service_level",
            field=models.CharField(
                choices=[("github", "GITHUB"), ("bitbucket", "BITBUCKET")],
                db_column="service_level",
                default="full_service",
                max_length=16,
                verbose_name="Service Level",
            ),
        ),
    ]
