# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.4 on 2022-05-23 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0040_customer__service_level"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="_service_level",
            field=models.CharField(
                choices=[("full_service", "FULL_SERVICE"), ("limited", "LIMITED")],
                db_column="service_level",
                default="full_service",
                max_length=16,
                verbose_name="Service Level",
            ),
        ),
    ]
