# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.5 on 2022-06-29 16:41

from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0041_alter_customer__service_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="created_at",
            field=models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="repo",
            name="created_at",
            field=models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False),
        ),
        migrations.AddField(
            model_name="repo",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="toolchainuser",
            name="modified_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
