# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.6 on 2023-02-07 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0042_customer_created_at_customer_modified_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="_access_mode",
            field=models.CharField(  # noqa: DJ01
                choices=[("allow", "ALLOW_ACCESS"), ("other", "REQUIRE_OTHER")],
                db_column="access_mode",
                default=None,
                max_length=10,
                null=True,
                verbose_name="Access mode",
            ),
        ),
    ]
