# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.6 on 2023-02-14 19:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("site", "0043_alter_customer__access_mode"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="_access_mode",
        ),
    ]
