# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

pex_binary(name="dump_redis_metadata", entry_point="dump_redis_metadata.py")
pex_binary(name="remote_cache_usage_reporter", entry_point="remote_cache_usage_reporter.py")
pex_binary(name="with_cas_token", entry_point="with_cas_token.py")
