# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(name="base", sources=["base.py"])

python_sources(name="service", sources=["service.py"])

python_sources(
    name="util",
    sources=["util.py", "db_config.py"],
)

python_tests(name="tests")
