# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.1 on 2019-06-05 21:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("workflow", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="StagingDirectory",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bucket", models.CharField(max_length=256)),
                ("dataset", models.CharField(max_length=256)),
                ("key_prefix", models.CharField(max_length=512)),
                ("created_at", models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name="TransformStagingDirectory",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                (
                    "staging_directory",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="buildsense.StagingDirectory"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="RotateStagingDirectory",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("rotate_after", models.DateTimeField()),
                (
                    "staging_directory",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="buildsense.StagingDirectory"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="CreateStagingDirectory",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("bucket", models.CharField(max_length=256)),
                ("dataset", models.CharField(max_length=256)),
                (
                    "staging_directory",
                    models.OneToOneField(
                        null=True, on_delete=django.db.models.deletion.CASCADE, to="buildsense.StagingDirectory"
                    ),
                ),
            ],
            options={"abstract": False},
        ),
    ]
