# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-17 17:07

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("buildsense", "0001_initial")]

    operations = [
        migrations.RemoveField(model_name="rotatestagingdirectory", name="staging_directory"),
        migrations.RemoveField(model_name="rotatestagingdirectory", name="work_unit"),
        migrations.RemoveField(model_name="transformstagingdirectory", name="staging_directory"),
        migrations.RemoveField(model_name="transformstagingdirectory", name="work_unit"),
        migrations.DeleteModel(name="CreateStagingDirectory"),
        migrations.DeleteModel(name="RotateStagingDirectory"),
        migrations.DeleteModel(name="StagingDirectory"),
        migrations.DeleteModel(name="TransformStagingDirectory"),
    ]
