# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()


pex_binary(name="depgraph_builder", entry_point="depgraph_builder_tool.py")
pex_binary(name="depgraph_inducer", entry_point="depgraph_inducer.py")
