# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.2 on 2020-01-22 21:42

import shortuuid
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ResolverSolution",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=shortuuid.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("last_update", models.DateTimeField(null=True)),
                ("leveldb_version", models.IntegerField(editable=False)),
                ("dependencies_digest", models.CharField(editable=False, max_length=64)),
                ("parameters_digest", models.CharField(editable=False, max_length=64)),
                ("_solution_state", models.CharField(db_column="state", default="pending", max_length=10)),
                ("_error_type", models.CharField(db_column="error_type", default="", max_length=24)),
                ("_result", models.TextField(max_length=8192)),
            ],
            options={"abstract": False},
        )
    ]
