# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.6 on 2020-05-14 17:52

import django.contrib.postgres.fields.jsonb
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0005_auto_20191115_1958"),
        ("dependency", "0002_cleanoldsolutions_periodicallycleanoldsolutions"),
    ]

    operations = [
        migrations.CreateModel(
            name="ResolveDependencies",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("solution_id", models.CharField(editable=False, max_length=22)),
                ("python_requirements", django.contrib.postgres.fields.jsonb.JSONField()),
                ("parameters", django.contrib.postgres.fields.jsonb.JSONField()),
            ],
            options={"abstract": False},
        ),
    ]
