# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1 on 2020-08-17 22:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dependency", "0003_resolvedependencies"),
    ]

    operations = [
        migrations.AlterField(model_name="resolvedependencies", name="parameters", field=models.JSONField()),
        migrations.AlterField(model_name="resolvedependencies", name="python_requirements", field=models.JSONField()),
    ]
