# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    dependencies=[
        ":services",
    ],
)

python_tests(name="tests")

resources(name="services", sources=["services.json"])
