# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.8 on 2021-10-12 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
    ]

    operations = [
        migrations.CreateModel(
            name="GenerateDepgraphForRepo",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("demo_repo_id", models.CharField(max_length=22)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
