# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.8 on 2021-10-14 19:40

import shortuuid
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [
        ("pants_demos_depgraph", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DemoRepo",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=shortuuid.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("repo_account", models.CharField(max_length=30)),
                ("repo_name", models.CharField(max_length=30)),
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("last_processed", models.DateTimeField(null=True)),
                ("result_location", models.CharField(max_length=256)),
                ("commit_sha", models.CharField(max_length=48)),
                ("branch_name", models.CharField(max_length=48)),
                (
                    "_processing_state",
                    models.CharField(
                        choices=[
                            ("not_processed", "NOT_PROCESSED"),
                            ("procssing", "PROCESSING"),
                            ("success", "SUCCESS"),
                            ("failure", "FAILURE"),
                        ],
                        db_column="state",
                        default="not_processed",
                        max_length=15,
                    ),
                ),
            ],
            options={
                "unique_together": {("repo_account", "repo_name")},
            },
        ),
    ]
