# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.12 on 2022-02-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pants_demos_depgraph", "0002_demorepo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demorepo",
            name="_processing_state",
            field=models.CharField(
                choices=[
                    ("not_processed", "NOT_PROCESSED"),
                    ("processing", "PROCESSING"),
                    ("success", "SUCCESS"),
                    ("failure", "FAILURE"),
                ],
                db_column="state",
                default="not_processed",
                max_length=15,
            ),
        ),
    ]
