# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.3 on 2022-03-09 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pants_demos_depgraph", "0003_alter_demorepo__processing_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorepo",
            name="num_of_targets",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
