# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.3 on 2022-03-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pants_demos_depgraph", "0004_demorepo_num_of_targets"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorepo",
            name="fail_reason",
            field=models.CharField(default="", max_length=256),
            preserve_default=False,
        ),
    ]
