# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.6 on 2022-07-25 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pants_demos_depgraph", "0005_demorepo_fail_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="demorepo",
            name="processing_time",
            field=models.DurationField(default=None, null=True),
        ),
    ]
