# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.1 on 2022-09-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pants_demos_depgraph", "0006_demorepo_processing_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demorepo",
            name="repo_account",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="demorepo",
            name="repo_name",
            field=models.CharField(max_length=256),
        ),
    ]
