# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.1 on 2019-06-05 21:42

import datetime

import django.contrib.postgres.fields
import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    initial = True

    dependencies = [("contenttypes", "0002_remove_content_type_name")]

    operations = [
        migrations.CreateModel(
            name="WorkUnit",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PEN", "pending"),
                            ("REA", "ready"),
                            ("LEA", "leased"),
                            ("SUC", "succeeded"),
                            ("INF", "infeasible"),
                        ],
                        default="REA",
                        max_length=3,
                    ),
                ),
                ("num_unsatisfied_requirements", models.IntegerField(default=0)),
                (
                    "created_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
                ),
                (
                    "last_attempt",
                    models.DateTimeField(db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
                ),
                (
                    "succeeded_at",
                    models.DateTimeField(db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
                ),
                ("leased_until", models.DateTimeField(db_index=True, default=None, null=True)),
                ("lease_holder", models.CharField(blank=True, db_index=True, default="", max_length=36)),
                ("node", models.CharField(blank=True, db_index=True, default="", max_length=100)),
                ("description", models.CharField(max_length=1024)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "creator",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created",
                        to="workflow.WorkUnit",
                    ),
                ),
                (
                    "payload_ctype",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.ContentType"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkUnitStateCountDelta",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ctype", models.IntegerField()),
                (
                    "from_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64), default=list, size=None
                    ),
                ),
                (
                    "to_tags",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=64), default=list, size=None
                    ),
                ),
                (
                    "from_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PEN", "pending"),
                            ("REA", "ready"),
                            ("LEA", "leased"),
                            ("SUC", "succeeded"),
                            ("INF", "infeasible"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "to_state",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("PEN", "pending"),
                            ("REA", "ready"),
                            ("LEA", "leased"),
                            ("SUC", "succeeded"),
                            ("INF", "infeasible"),
                        ],
                        max_length=3,
                    ),
                ),
                ("delta", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="WorkUnitStateCount",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("shard", models.IntegerField()),
                (
                    "tags",
                    django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=64), size=None),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("PEN", "pending"),
                            ("REA", "ready"),
                            ("LEA", "leased"),
                            ("SUC", "succeeded"),
                            ("INF", "infeasible"),
                        ],
                        max_length=3,
                    ),
                ),
                ("count", models.IntegerField(default=0)),
                (
                    "ctype",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workunit_state_counts",
                        to="contenttypes.ContentType",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkUnitRequirement",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="source+", to="workflow.WorkUnit"
                    ),
                ),
                (
                    "target",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="target+", to="workflow.WorkUnit"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="workunit",
            name="requirements",
            field=models.ManyToManyField(
                blank=True, related_name="required_by", through="workflow.WorkUnitRequirement", to="workflow.WorkUnit"
            ),
        ),
        migrations.CreateModel(
            name="WorkExceptionLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "category",
                    models.CharField(choices=[("TRANSIENT", "transient"), ("PERMANENT", "permanent")], max_length=20),
                ),
                ("message", models.CharField(max_length=50000)),
                ("stacktrace", models.TextField(blank=True)),
                ("search_vector", django.contrib.postgres.search.SearchVectorField(null=True)),
                (
                    "work_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="errors", to="workflow.WorkUnit"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="workunitstatecount",
            index=django.contrib.postgres.indexes.GinIndex(fields=["tags"], name="workflow_wo_tags_ce4054_gin"),
        ),
        migrations.AlterUniqueTogether(
            name="workunitstatecount", unique_together={("shard", "ctype", "tags", "state")}
        ),
        migrations.AlterUniqueTogether(name="workunitrequirement", unique_together={("source", "target")}),
        migrations.AddIndex(
            model_name="workunit",
            index=models.Index(fields=["state", "payload_ctype"], name="workflow_wo_state_ce2888_idx"),
        ),
        migrations.AddIndex(
            model_name="workunit",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="workflow_wo_search__df6708_gin"
            ),
        ),
        migrations.AddIndex(
            model_name="workexceptionlog",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="workflow_wo_search__6531f1_gin"
            ),
        ),
    ]
