# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-02 14:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("workflow", "0001_initial")]

    operations = [
        migrations.AlterField(
            model_name="workexceptionlog",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        )
    ]
