# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-11 18:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("workflow", "0002_auto_20190902_1451")]

    operations = [
        migrations.AlterField(
            model_name="workexceptionlog",
            name="category",
            field=models.CharField(
                choices=[("ADVISORY", "advisory"), ("TRANSIENT", "transient"), ("PERMANENT", "permanent")],
                max_length=20,
            ),
        )
    ]
