# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-13 22:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("contenttypes", "0002_remove_content_type_name"), ("workflow", "0003_auto_20190911_1829")]

    operations = [
        migrations.RemoveIndex(model_name="workunitstatecount", name="workflow_wo_tags_ce4054_gin"),
        migrations.RemoveField(model_name="workunitstatecountdelta", name="from_tags"),
        migrations.RemoveField(model_name="workunitstatecountdelta", name="to_tags"),
        migrations.AlterUniqueTogether(name="workunitstatecount", unique_together={("shard", "ctype", "state")}),
        migrations.RemoveField(model_name="workunitstatecount", name="tags"),
    ]
