# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.5 on 2019-11-15 19:58

from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [("workflow", "0004_auto_20190913_2212")]

    operations = [
        migrations.AlterField(
            model_name="workexceptionlog",
            name="timestamp",
            field=models.DateTimeField(db_index=True, default=toolchain.base.datetime_tools.utcnow),
        )
    ]
