# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-29 22:11

import datetime

import django.db.models.deletion
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("workflow", "0005_auto_20191115_1958"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workunit",
            name="created_at",
            field=models.DateTimeField(
                db_index=True, default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc), editable=False
            ),
        ),
        migrations.AlterField(
            model_name="workunit",
            name="payload_ctype",
            field=models.ForeignKey(
                editable=False, on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"
            ),
        ),
    ]
