# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-15 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0006_auto_20201229_2211"),
    ]

    operations = [
        migrations.AlterField(
            model_name="workexceptionlog",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="workunitrequirement",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="workunitstatecount",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="workunitstatecountdelta",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
