# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.5 on 2022-06-03 21:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicallySyncAmberfloCustomer",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("customer_id", models.CharField(editable=False, max_length=22)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
