# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.6 on 2022-07-27 20:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amberflo_integration", "0003_rename_periodicallycreatecustomersync_periodicallycreateamberflocustomersync"),
    ]

    operations = [
        migrations.CreateModel(
            name="AmberfloCustomerMTDMetrics",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("customer_id", models.CharField(db_index=True, editable=False, max_length=22)),
                ("metric_year", models.PositiveSmallIntegerField(db_index=True)),
                ("metric_month", models.PositiveSmallIntegerField(db_index=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
                ("cache_read_bytes", models.PositiveBigIntegerField()),
                ("cache_write_bytes", models.PositiveBigIntegerField()),
            ],
            options={
                "unique_together": {("customer_id", "metric_year", "metric_month")},
            },
        ),
    ]
