# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.6 on 2022-07-29 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amberflo_integration", "0004_amberflocustomermtdmetrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="amberflocustomermtdmetrics",
            name="customer_slug",
            field=models.CharField(max_length=64, null=True),  # noqa: DJ01
        ),
    ]
