# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1 on 2022-08-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("amberflo_integration", "0005_amberflocustomermtdmetrics_customer_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="amberflocustomermtdmetrics",
            name="customer_slug",
            field=models.CharField(default="", max_length=64),
            preserve_default=False,
        ),
    ]
