# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

python_tests(name="tests")

pex_binary(
    name="rotate-aws-creds",
    entry_point="rotate_aws_creds.py",
)
