# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-08-16 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("workflow", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ProcessPantsRun",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("customer_id", models.CharField(max_length=64)),
                ("repo_id", models.CharField(max_length=64)),
                ("user_api_id", models.CharField(max_length=22)),
                ("run_id", models.CharField(max_length=512)),
            ],
            options={"abstract": False},
        )
    ]
