# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.7 on 2020-06-23 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0005_auto_20191115_1958"),
        ("ingestion", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessQueuedBuilds",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("customer_id", models.CharField(max_length=64)),
                ("repo_id", models.CharField(max_length=64)),
                ("bucket", models.CharField(max_length=64)),
                ("key", models.CharField(max_length=512)),
                ("num_of_builds", models.PositiveIntegerField()),
            ],
            options={"abstract": False},
        ),
    ]
