# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2 on 2021-04-21 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("ingestion", "0002_processqueuedbuilds"),
    ]

    operations = [
        migrations.CreateModel(
            name="IndexPantsMetrics",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("customer_id", models.CharField(max_length=64)),
                ("repo_id", models.CharField(max_length=64)),
                ("user_api_id", models.CharField(max_length=22)),
                ("run_id", models.CharField(max_length=512)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
