# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.10 on 2021-12-21 18:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0005_alter_processpantsrun__run_state"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexpantsmetrics",
            name="_run_state",
            field=models.CharField(  # noqa: DJ01
                choices=[("active", "ACTIVE"), ("deleted", "DELETED")],
                db_column="state",
                default="active",
                max_length=10,
                null=True,
            ),
        ),
    ]
