# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.10 on 2021-12-24 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("ingestion", "0006_alter_indexpantsmetrics__run_state"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProcessBuildDataRetention",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("repo_id", models.CharField(editable=False, max_length=64, unique=True)),
                ("retention_days", models.PositiveIntegerField(default=9125)),
                ("period_minutes", models.PositiveIntegerField(null=True)),
                ("dry_run", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
