# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.10 on 2021-12-27 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("ingestion", "0007_processbuilddataretention"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigureRepoMetricsBucket",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("repo_id", models.CharField(editable=False, max_length=64, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
