# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.10 on 2021-12-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0008_configurerepometricsbucket"),
    ]

    operations = [
        migrations.AlterField(
            model_name="indexpantsmetrics",
            name="_run_state",
            field=models.CharField(
                choices=[("active", "ACTIVE"), ("deleted", "DELETED")],
                db_column="state",
                default="active",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="processpantsrun",
            name="_run_state",
            field=models.CharField(
                choices=[("active", "ACTIVE"), ("deleted", "DELETED")],
                db_column="state",
                default="active",
                max_length=10,
            ),
        ),
    ]
