# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.11 on 2022-01-30 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("ingestion", "0009_auto_20211228_0049"),
    ]

    operations = [
        migrations.CreateModel(
            name="MoveBuild",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("customer_id", models.CharField(max_length=22)),
                ("repo_id", models.CharField(max_length=22)),
                ("run_id", models.CharField(max_length=512)),
                ("from_user_api_id", models.CharField(max_length=22)),
                ("to_user_api_id", models.CharField(max_length=22)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
