# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.1 on 2022-09-22 20:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0010_movebuild"),
    ]

    operations = [
        migrations.AddField(
            model_name="indexpantsmetrics",
            name="repo_full_name",
            field=models.CharField(default=None, max_length=120, null=True),  # noqa: DJ01
        ),
        migrations.AddField(
            model_name="processbuilddataretention",
            name="repo_full_name",
            field=models.CharField(default=None, max_length=120, null=True),  # noqa: DJ01
        ),
        migrations.AddField(
            model_name="processpantsrun",
            name="repo_full_name",
            field=models.CharField(default=None, max_length=120, null=True),  # noqa: DJ01
        ),
    ]
