# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.6 on 2023-02-09 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0011_indexpantsmetrics_repo_full_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexpantsmetrics",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="movebuild",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="processpantsrun",
            name="customer_id",
        ),
        migrations.RemoveField(
            model_name="processqueuedbuilds",
            name="customer_id",
        ),
        migrations.AddField(
            model_name="indexpantsmetrics",
            name="_customer_id",
            field=models.CharField(db_column="customer_id", default=None, max_length=64, null=True),  # noqa: DJ01
        ),
        migrations.AddField(
            model_name="movebuild",
            name="_customer_id",
            field=models.CharField(db_column="customer_id", default=None, max_length=64, null=True),  # noqa: DJ01
        ),
        migrations.AddField(
            model_name="processpantsrun",
            name="_customer_id",
            field=models.CharField(db_column="customer_id", default=None, max_length=64, null=True),  # noqa: DJ01
        ),
        migrations.AddField(
            model_name="processqueuedbuilds",
            name="_customer_id",
            field=models.CharField(db_column="customer_id", default=None, max_length=64, null=True),  # noqa: DJ01
        ),
    ]
