# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.6 on 2023-02-09 16:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0012_remove_indexpantsmetrics_customer_id_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="indexpantsmetrics",
            index=models.Index(fields=["repo_id", "run_id"], name="ingestion_i_repo_id_81af10_idx"),
        ),
    ]
