# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.6 on 2023-02-10 18:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("ingestion", "0013_indexpantsmetrics_ingestion_i_repo_id_81af10_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="indexpantsmetrics",
            name="_customer_id",
        ),
        migrations.RemoveField(
            model_name="movebuild",
            name="_customer_id",
        ),
        migrations.RemoveField(
            model_name="processpantsrun",
            name="_customer_id",
        ),
        migrations.RemoveField(
            model_name="processqueuedbuilds",
            name="_customer_id",
        ),
    ]
