# Copyright 2018 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

from django.core.management.base import BaseCommand

from toolchain.crawler.maven.models import BINARY, SOURCE, IndexLatestVersionOfMavenArtifact
from toolchain.packagerepo.maven.coordinates import GACoordinates


# Reminder that Django requires this class to be named 'Command'.
# The command name is the module name.
class Command(BaseCommand):
    """Seeds the indexer with the top N maven artifacts.maven.

    The sorted_artifacts_file can be generated by running:

    ```
    ./python src/python/toolchain/crawler/main/worker/manage.py toposort \
      --coords=/path/to/maven_artifacts.csv \
      --deps=/path/to/maven_artifact_dependencies.csv \
      --write-path=/path/to/sorted_artifacts_output.txt
    ```

    The maven_artifacts and maven_artifacts_dependencies csv files can be downloaded from
    https://crawler.toolchainlabs.com/maven/dump/
    """

    help = "Seed the indexer with the top N maven artifacts."

    def add_arguments(self, parser):
        parser.add_argument(
            "--number", default=10, type=int, help="Number of maven artifacts to seed the indexer with."
        )
        parser.add_argument(
            "--sorted-artifacts-file",
            required=True,
            help="Path to sorted maven artifacts .txt file. Generate this with the toposorter command.",
        )
        parser.add_argument("--binary", action="store_true", default=False, help="Index binary jars.")
        parser.add_argument("--source", action="store_true", default=False, help="Index source jars.")

    def get_top_N_maven_artifacts(self, number, sorted_artifacts_file):
        """Returns a list of GACoordinates for the top N maven artifacts."""
        with open(sorted_artifacts_file, "rb") as f:
            lines = [f.readline().strip() for i in range(number)]
        return [GACoordinates(*line.split(":")) for line in lines]

    def handle(self, *args, **options):
        index_binary_jars = options["binary"]
        index_source_jars = options["source"]
        if not index_binary_jars and not index_source_jars:
            print("Must pass one or both of ['--binary', '--source']")
            return

        sorted_artifacts_file = options["sorted_artifacts_file"]

        top_maven_artifacts = self.get_top_N_maven_artifacts(
            number=options["number"], sorted_artifacts_file=sorted_artifacts_file
        )

        for artifact in top_maven_artifacts:
            if index_binary_jars:
                IndexLatestVersionOfMavenArtifact.for_coordinates_and_kind(artifact, BINARY)
            if index_source_jars:
                IndexLatestVersionOfMavenArtifact.for_coordinates_and_kind(artifact, SOURCE)
