# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.4 on 2022-04-28 20:52

import django.db.models.deletion
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicallySyncStripeCustomer",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("customer_id", models.CharField(editable=False, max_length=22)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SubscribedCustomer",
            fields=[
                (
                    "customer_id",
                    models.CharField(
                        db_index=True, editable=False, max_length=22, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("stripe_customer_id", models.CharField(db_index=True, editable=False, max_length=25, unique=True)),
                ("created", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("modified", models.DateTimeField(auto_now=True)),
                (
                    "_subs_state",
                    models.CharField(
                        choices=[("active", "ACTIVE"), ("inactive", "INACTIVE")],
                        db_column="state",
                        default="active",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
