# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.4 on 2022-05-27 19:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribedcustomer",
            name="stripe_subscription_id",
            field=models.CharField(default="", max_length=25),
        ),
    ]
