# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.5 on 2022-06-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_integration", "0002_subscribedcustomer_stripe_subscription_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscribedcustomer",
            name="stripe_customer_id",
            field=models.CharField(db_index=True, editable=False, max_length=48, unique=True),
        ),
        migrations.AlterField(
            model_name="subscribedcustomer",
            name="stripe_subscription_id",
            field=models.CharField(default="", max_length=48),
        ),
    ]
