# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.5 on 2022-06-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_integration", "0003_alter_subscribedcustomer_stripe_customer_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicallysyncstripecustomer",
            name="force_run",
            field=models.BooleanField(default=False),
        ),
    ]
