# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.6 on 2022-07-08 18:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
        ("stripe_integration", "0005_periodicallycreatecustomersync"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="PeriodicallyCreateCustomerSync",
            new_name="PeriodicallyCreateStripeCustomerSync",
        ),
    ]
