# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1 on 2022-08-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_integration", "0007_subscribedcustomer_customer_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribedcustomer",
            name="plan_name",
            field=models.CharField(max_length=48, null=True),  # noqa: DJ01
        ),
        migrations.AddField(
            model_name="subscribedcustomer",
            name="plan_price_text",
            field=models.CharField(max_length=48, null=True),  # noqa: DJ01
        ),
        migrations.AddField(
            model_name="subscribedcustomer",
            name="trial_end",
            field=models.DateField(null=True),
        ),
    ]
