# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.1 on 2022-09-07 15:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_integration", "0009_alter_subscribedcustomer_customer_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscribedcustomer",
            name="payout_outside_of_stripe",
            field=models.BooleanField(default=False),
        ),
    ]
