# Copyright 2023 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.1.5 on 2023-01-04 21:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("stripe_integration", "0010_subscribedcustomer_payout_outside_of_stripe"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicallysyncstripecustomer",
            name="customer_slug",
            field=models.CharField(max_length=64, null=True),  # noqa: DJ01
        ),
    ]
