# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.1 on 2019-06-05 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("workflow", "0001_initial"), ("webresource", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="FetchURL",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("url", models.URLField(db_index=True, max_length=500)),
                ("last_http_status", models.IntegerField(db_index=True, null=True)),
                (
                    "web_resource",
                    models.ForeignKey(
                        null=True, on_delete=django.db.models.deletion.SET_NULL, to="webresource.WebResource"
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="fetchurl",
            constraint=models.UniqueConstraint(
                condition=models.Q(web_resource__isnull=True), fields=("url",), name="single_pending_fetch"
            ),
        ),
    ]
