# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    dependencies=[
        "src/python/toolchain/django/webresource/migrations",  # referenced in migration dependencies
        "src/python/toolchain/workflow/migrations",  # referenced in migration dependencies
    ],
)
