# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.5 on 2020-04-03 17:00

import shortuuid
from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GithubRepo",
            fields=[
                (
                    "id",
                    models.CharField(
                        db_index=True,
                        default=shortuuid.uuid,
                        editable=False,
                        max_length=22,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("repo_id", models.CharField(db_index=True, max_length=10)),
                (
                    "_repo_state",
                    models.CharField(db_column="repo_state", db_index=True, default="active", max_length=10),
                ),
                ("name", models.CharField(max_length=22)),
                ("customer_id", models.CharField(max_length=22)),
                ("install_id", models.CharField(editable=False, max_length=64)),
                ("created_at", models.DateTimeField(default=toolchain.base.datetime_tools.utcnow, editable=False)),
                ("webhooks_secret", models.CharField(max_length=64)),
                ("webhook_id", models.CharField(default="", max_length=10)),
            ],
            options={"abstract": False},
        ),
    ]
