# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.7 on 2020-06-12 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0005_auto_20191115_1958"),
        ("github_integration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConfigureGithubRepo",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("repo_id", models.CharField(editable=False, max_length=22)),
            ],
            options={"abstract": False},
        ),
    ]
