# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.3 on 2020-11-17 16:42

from django.db import migrations, models

import toolchain.base.datetime_tools


class Migration(migrations.Migration):
    dependencies = [
        ("github_integration", "0002_configuregithubrepo"),
    ]

    operations = [
        migrations.AddField(
            model_name="githubrepo",
            name="last_updated",
            field=models.DateTimeField(default=toolchain.base.datetime_tools.utcnow),
        ),
    ]
