# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.4 on 2020-12-22 23:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0005_auto_20191115_1958"),
        ("github_integration", "0003_githubrepo_last_updated"),
    ]

    operations = [
        migrations.CreateModel(
            name="GithubRepoStatsConfiguration",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("repo_id", models.CharField(editable=False, max_length=22)),
                ("period_minutes", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
