# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.4 on 2021-06-04 19:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github_integration", "0004_githubrepostatsconfiguration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="githubrepo",
            name="name",
            field=models.CharField(max_length=64),
        ),
    ]
