# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.3 on 2022-03-03 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github_integration", "0005_alter_githubrepo_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuregithubrepo",
            name="_extra_events",
            field=models.CharField(db_column="extra_events", default="", max_length=128),
        ),
    ]
