# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 4.0.4 on 2022-05-06 19:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("github_integration", "0006_configuregithubrepo__extra_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="configuregithubrepo",
            name="force_update",
            field=models.BooleanField(default=False),
        ),
    ]
