# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

python_tests(
    name="tests",
    dependencies=[
        "src/python/toolchain/django/site",  # Used in `conftest.py`.
    ],
)

python_test_utils(name="test_utils")
