# Copyright 2018 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    dependencies=[
        ":templates",
    ],
)

python_tests(name="tests")

resources(
    name="templates",
    sources=["jinja2/**/*"],
)

python_test_utils(name="test_utils")
