#!/usr/bin/env bash
# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

set -euo pipefail

ROOT="$(git rev-parse --show-toplevel)"

SCRIPT="$(
  cd "$(dirname "${BASH_SOURCE[0]}")" && pwd -P | sed "s|${ROOT}|.|"
)/$(basename "${BASH_SOURCE[0]}")"

cd "${ROOT}"

CI_IMAGE_URI="$(yq r ./.circleci/config.yml 'defaults.default_image.image')"

log() {
  echo >&2 "$@"
}

fix_references() {
  log "Updating ci image references to ${CI_IMAGE_URI}"

  log "Fixing ./.envrc.ci-image."
  cat << EOF > ./.envrc.ci-image
# This file is auto-generated by ${SCRIPT}
# Edit .defaults.default_image.image in .circleci/config.yml and then re-generate.

# Derived from .circleci/config.yml.
export CI_IMAGE_URI=${CI_IMAGE_URI}
EOF

}

check_references() {
  fix_references

  log "Checking for reference diffs ..."
  git diff --exit-code HEAD -- \
    ./.envrc.ci-image ||
    {
      log
      log "CI image reference differences found, please commit the diff."
      exit 1
    }
}

usage() {
  if (($# > 0)); then
    exec >&2
  fi

  cat << USAGE
Ensures the toolchain CI image is setup for BuildFarm dogfooding.

Usage: $0 -h
Usage: $0 [-c]

 -h
   Print out this help message.

 -c
   Only check that the CI image references are up to date, don't fix the references if broken.
USAGE

  if (($# > 0)); then
    echo -e "\\n$*"
    exit 1
  else
    exit 0
  fi
}

action=fix_references
while getopts "hc" opt; do
  case "${opt}" in
    h)
      usage
      ;;
    c)
      action=check_references
      ;;
    *)
      usage "Invalid option: -${OPTARG}"
      ;;
  esac
done
shift "$((OPTIND - 1))"

if (($# > 0)); then
  usage "Unexpected arguments: $*"
fi

eval "${action}"
