{
 "title": "OpenTelemetry Collector",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Collector", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Spans",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(otelcol_receiver_accepted_spans{service=\"otel-collector\"}[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(irate(otelcol_exporter_sent_spans{service=\"otel-collector\"}[1m]))",
     "legendFormat": "Outbound"
    }
   ]
  },
  {
   "title": "Spans by Receiver",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(otelcol_receiver_accepted_spans{service=\"otel-collector\"}[1m])) by (receiver)",
     "legendFormat": "{{receiver}}"
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(irate(otelcol_receiver_refused_spans{service=\"otel-collector\"}[1m]))",
     "legendFormat": "Inbound"
    },
    {
     "expr": "sum(irate(otelcol_exporter_send_failed_spans{service=\"otel-collector\"}[1m]))",
     "legendFormat": "OutBound"
    }
   ]
  }
 ]
}