{
 "title": "Pants Anonymous Telemetry",
 "time": { "from": "now-3M", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "query": "InfluxDB-pants-telemetry" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Run Duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"anonymous-telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"duration\")\n  |> filter(fn: (r) => r[\"_field\"] == \"val\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Num of goals",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "query": "from(bucket: \"anonymous-telemetry\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"num_goals\")\n  |> filter(fn: (r) => r[\"_field\"] == \"val\")\n  |> aggregateWindow(every: v.windowPeriod, fn: mean, createEmpty: false)\n  |> yield(name: \"mean\")"
    }
   ]
  },
  {
   "title": "Unique Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "query": "from(bucket: \"anonymous-telemetry\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"uniques\")\n|> filter(fn: (r) => r[\"_field\"] == \"user\")\n|> group()|> aggregateWindow(every: 1d,fn: (column, tables=<-) => tables \n|> distinct() \n|> count())\n"
    }
   ]
  },
  {
   "title": "Unique Repos",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"anonymous-telemetry\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"uniques\")\n|> filter(fn: (r) => r[\"_field\"] == \"repo\")\n|> group()|> aggregateWindow(every: 1d,fn: (column, tables=<-) => tables \n|> distinct() \n|> count())\n"
    }
   ]
  },
  {
   "title": "Num of runs per month",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "query": "from(bucket: \"anonymous-telemetry\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"uniques\")\n|> filter(fn: (r) => r[\"_field\"] == \"repo\")\n|> group()|> aggregateWindow(every: 30d,fn: (column, tables=<-) => tables \n|> count())\n"
    }
   ]
  },
  {
   "title": "Num of runs per day",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"anonymous-telemetry\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r[\"_measurement\"] == \"uniques\")\n|> filter(fn: (r) => r[\"_field\"] == \"repo\")\n|> group()|> aggregateWindow(every: 1d,fn: (column, tables=<-) => tables \n|> count())\n"
    }
   ]
  }
 ]
}