{
 "title": "Remote cache client metrics",
 "tags": [
  "Toolchain",
  "Remoting"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "repo",
    "query": "buckets()\n|> filter(fn: (r) => contains(value: r.name, set: [\"_tasks\", \"_monitoring\", \"default\"]) == false)\n|> keep(columns: [\"name\"])"
   },
   {
    "name": "context",
    "query": "from(bucket: \"${repo}\")\n|> range(start: -1h, stop: now())\n|> filter(fn: (r) => (r._measurement == \"workunits\"))\n|> keep(columns: [\"context\"])\n|> group()\n|> distinct(column: \"context\")\n|> limit(n: 25)"
   },
   { "name": "datasource", "query": "InfluxDB-buildsense" },
   {
    "name": "goal",
    "query": "from(bucket: \"${repo}\")\n|> range(start: -24h, stop: now())\n|> filter(fn: (r) => (r._measurement == \"indicators\"))\n|> keep(columns: [\"goals\"])\n|> group()\n|> distinct(column: \"goals\")\n|> limit(n: 25)"
   }
  ]
 },
 "panels": [
  {
   "title": "Cache hits (average per-build)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "requests = from(bucket: \"${repo}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"indicators\" and r._field == \"hit_fraction_remote\")\n|> filter(fn: (r) => exists r.goals and contains(value: r.goals, set: ${goal:json}) and contains(value: r.context, set: ${context:json}))\n|> keep(columns: [\"_value\"])\n|> mean()\n|> yield()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time saved (average per-build)",
   "type": "stat",
   "description": "The average time saved thanks to caching processes.\n\nNote that this metric is relative to the counterfactual of having no local cache hits and running all processes sequentially, rather than using Pants's concurrency.\n\nFor CI uses, you should also consider the time saved from remote caching thanks to not downloading/uploading `~/.cache/pants` to your CI like is normally done.",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${repo}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"indicators\" and r._field == \"saved_cpu_time_remote\")\n|> filter(fn: (r) => exists r.goals and contains(value: r.goals, set: ${goal:json}) and contains(value: r.context, set: ${context:json}))\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> mean()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Hit fraction (windowed average)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${repo}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"indicators\" and r._field == \"hit_fraction_remote\")\n|> filter(fn: (r) => exists r.goals and contains(value: r.goals, set: ${goal:json}) and contains(value: r.context, set: ${context:json}))\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> aggregateWindow(every: 3h, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time saved (windowed average)",
   "type": "timeseries",
   "description": "See the description of \"Time saved (average per-build)\" for this metric's nuances.",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${repo}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"indicators\" and r._field == \"saved_cpu_time_remote\")\n|> filter(fn: (r) => exists r.goals and contains(value: r.goals, set: ${goal:json}) and contains(value: r.context, set: ${context:json}))\n|> keep(columns: [\"_time\", \"_field\", \"_value\"])\n|> aggregateWindow(every: 3h, fn: mean, createEmpty: false)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cache hits (per-build)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 11, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${repo}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"indicators\" and r._field == \"hit_fraction_remote\")\n|> filter(fn: (r) => exists r.goals and contains(value: r.goals, set: ${goal:json}) and contains(value: r.context, set: ${context:json}))\n|> yield(name: \"hit_fraction_remote\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Time saved (per-build)",
   "type": "timeseries",
   "description": "See the description of \"Time saved (average per-build)\" for this metric's nuances.",
   "gridPos": { "h": 9, "w": 11, "x": 11, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "from(bucket: \"${repo}\")\n|> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn: (r) => r._measurement == \"indicators\" and r._field == \"saved_cpu_time_remote\")\n|> filter(fn: (r) => exists r.goals and contains(value: r.goals, set: ${goal:json}) and contains(value: r.context, set: ${context:json}))\n|> yield(name: \"saved_cpu_time_remote\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}