{
 "title": "Remote Cache / Storage",
 "description": "Storage specific monitoring (storage-server, Redis, & EFS)",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(grpc_server_handled_total, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests (by customer)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(toolchain_storage_requests_handled_total{namespace=\"$namespace\"}[$__interval])) by (reapi_instance)",
     "legendFormat": "{{reapi_instance}}"
    }
   ]
  },
  {
   "title": "Requests (by operation)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "sum(increase(toolchain_storage_requests_handled_total{namespace=\"$namespace\"}[$__interval])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "p50 read latency by driver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"file\", operation=\"read\"}[$__interval])))",
     "legendFormat": "file"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"size_split\", operation=\"read\"}[$__interval])))",
     "legendFormat": "size_split"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"redis\", operation=\"read\"}[$__interval])))",
     "legendFormat": "redis"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"fast_slow\", operation=\"read\"}[$__interval])))",
     "legendFormat": "fast_slow"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"redis_direct\", operation=\"read\"}[$__interval])))",
     "legendFormat": "redis_direct"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"sharded\", operation=\"read\"}[$__interval])))",
     "legendFormat": "sharded"
    }
   ]
  },
  {
   "title": "p50 write latency by driver",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"file\", operation=\"write\"}[$__interval])))",
     "legendFormat": "file"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"size_split\", operation=\"write\"}[$__interval])))",
     "legendFormat": "size_split"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"redis\", operation=\"write\"}[$__interval])))",
     "legendFormat": "redis"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"fast_slow\", operation=\"write\"}[$__interval])))",
     "legendFormat": "fast_slow"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"redis_direct\", operation=\"write\"}[$__interval])))",
     "legendFormat": "redis_direct"
    },
    {
     "expr": "histogram_quantile(0.5, sum by(le) (irate(toolchain_storage_requests_handling_seconds_bucket{namespace=\"$namespace\", driver=\"sharded\", operation=\"write\"}[$__interval])))",
     "legendFormat": "sharded"
    }
   ]
  },
  {
   "title": "Bandwidth",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "API Bytes In / Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_bytes_written_total{container=\"remoting-storage-server\", namespace=~\"$namespace\"}[$__interval]))",
       "legendFormat": "Write / Out"
      },
      {
       "expr": "sum(increase(toolchain_storage_bytes_read_total{container=\"remoting-storage-server\", namespace=~\"$namespace\"}[$__interval]))",
       "legendFormat": "Read / In"
      }
     ]
    },
    {
     "title": "Pod Network In/Out",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(irate(container_network_transmit_bytes_total{namespace=~\"$namespace\", pod=~\".*remoting-storage-server.*\"}[4h:5m]))",
       "legendFormat": "Net Out"
      },
      {
       "expr": "sum(irate(container_network_receive_bytes_total{namespace=~\"$namespace\", pod=~\".*remoting-storage-server.*\"}[4h:5m]))",
       "legendFormat": "Net In"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis [as seen by storage]",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redis Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_redis_requests_total{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Redis Driver by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_find_missing_blobs_total{namespace=\"$namespace\", job=\"remoting-storage-server\", driver=\"redis_direct\"}[$__interval]))  ",
       "legendFormat": "find missing blobs"
      },
      {
       "expr": "sum(increase(toolchain_storage_blobs_read_total{namespace=\"$namespace\", job=\"remoting-storage-server\", driver=\"redis_direct\"}[$__interval]))  ",
       "legendFormat": "reads"
      },
      {
       "expr": "sum(increase(toolchain_storage_blobs_written_total{namespace=\"$namespace\", job=\"remoting-storage-server\", driver=\"redis_direct\"}[$__interval]))",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "Redis Connect Errors (a/s/b New Client)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_redis_connect_failed_total{namespace=\"$namespace\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Redis Connection Pool Get Delay (Old Client)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Redis Disconnects (a/s/b New Client)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_redis_disconnected_total{namespace=\"$namespace\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Redis Connection Pool Errors (a/s/b Old Client)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_redis_get_connection_duration_seconds_count{namespace=\"$namespace\", job=\"remoting-storage-server\", result=\"error\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Cancellations (a/s/b New Client)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_redis_request_cancelled{namespace=\"$namespace\"}[$__interval]))"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "metricName": "EngineCPUUtilization", "namespace": "AWS/ElastiCache", "region": "default", "statistic": "Sum" }
     ]
    },
    {
     "title": "Redis Usage by Customer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "toolchain_remote_cache_usage_bytes{storage_type=\"redis\"}",
       "legendFormat": "{{customer}}"
      }
     ]
    },
    {
     "title": "Memory Usage Percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "*" },
       "metricName": "DatabaseMemoryUsagePercentage",
       "namespace": "AWS/ElastiCache",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "*" },
       "metricName": "Evictions",
       "namespace": "AWS/ElastiCache",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "remoting-storage-rg-1-002" },
       "metricName": "ReplicationLag",
       "namespace": "AWS/ElastiCache",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Redis New Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "*" },
       "metricName": "NewConnections",
       "namespace": "AWS/ElastiCache",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Redis Request Queued Duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (irate(toolchain_storage_redis_request_queued_duration_seconds_bucket{namespace=\"$namespace\"}[$__interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (increase(toolchain_storage_redis_request_queued_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (increase(toolchain_storage_redis_request_queued_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(toolchain_storage_redis_request_queued_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (increase(toolchain_storage_redis_request_queued_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "EFS",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Read / Write (Bytes)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "Write",
       "dimensions": { "FileSystemId": "fs-0da12c5381f11d884" },
       "metricName": "DataWriteIOBytes",
       "namespace": "AWS/EFS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "alias": "Read",
       "dimensions": { "FileSystemId": "fs-0da12c5381f11d884" },
       "metricName": "DataReadIOBytes",
       "namespace": "AWS/EFS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Throughput",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "alias": "Allocation",
       "dimensions": { "FileSystemId": "fs-0da12c5381f11d884" },
       "metricName": "PermittedThroughput",
       "namespace": "AWS/EFS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "alias": "Observed (metered)",
       "dimensions": { "FileSystemId": "fs-0da12c5381f11d884" },
       "metricName": "MetadataIOBytes",
       "namespace": "AWS/EFS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "alias": "Observed (actual)",
       "dimensions": { "FileSystemId": "fs-0da12c5381f11d884" },
       "metricName": "TotalIOBytes",
       "namespace": "AWS/EFS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Total Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "dimensions": { "FileSystemId": "fs-0da12c5381f11d884", "StorageClass": "Total" },
       "metricName": "StorageBytes",
       "namespace": "AWS/EFS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Burst Credits",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "dimensions": { "FileSystemId": "fs-0da12c5381f11d884" },
       "metricName": "BurstCreditBalance",
       "namespace": "AWS/EFS",
       "queryMode": "Metrics",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "EFS Usage by Customer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "toolchain_remote_cache_usage_bytes{storage_type=\"efs\"}",
       "legendFormat": "{{customer}}"
      }
     ]
    }
   ]
  }
 ]
}