{
 "title": "Storage Analysis",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "operation", "query": "find_missing_blobs,read,write" }
  ]
 },
 "panels": [
  { "title": "Overall -- gRPC", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Storage Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_handled_total{job=\"remoting-storage-server\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage Errors (by Type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(grpc_server_handled_total{job=\"remoting-storage-server\", grpc_code!~\"OK|NotFound\"}[$__interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Storage (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by (le) (irate(grpc_server_handling_seconds_bucket{job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (irate(grpc_server_handling_seconds_bucket{job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (irate(grpc_server_handling_seconds_bucket{job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(grpc_server_handling_seconds_bucket{job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (irate(grpc_server_handling_seconds_bucket{job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(grpc_server_handling_seconds_bucket{job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P99"
    }
   ]
  },
  { "title": "Overall -- Storage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Storage Requests by Operation",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(toolchain_storage_requests_handled_total{job=\"remoting-storage-server\"}[$__interval])) by (operation)",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Reads - Time to First Byte",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(toolchain_storage_time_to_first_byte_seconds_bucket{job=\"remoting-storage-server\", driver=\"redis_direct\"}[$__interval])))",
     "legendFormat": "P90 (Direct)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (irate(toolchain_storage_time_to_first_byte_seconds_bucket{job=\"remoting-storage-server\", driver=\"redis_direct\"}[$__interval])))",
     "legendFormat": "P95 (Direct)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(toolchain_storage_time_to_first_byte_seconds_bucket{job=\"remoting-storage-server\", driver=\"redis_direct\"}[$__interval])))",
     "legendFormat": "P99 (Direct)"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(toolchain_storage_time_to_first_byte_seconds_bucket{job=\"remoting-storage-server\", driver=\"redis\"}[$__interval])))",
     "legendFormat": "P90 (Chunked)"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (irate(toolchain_storage_time_to_first_byte_seconds_bucket{job=\"remoting-storage-server\", driver=\"redis\"}[$__interval])))",
     "legendFormat": "P95 (Chunked)"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(toolchain_storage_time_to_first_byte_seconds_bucket{job=\"remoting-storage-server\", driver=\"redis\"}[$__interval])))",
     "legendFormat": "P99 (Chunked)"
    }
   ]
  },
  {
   "title": "Bytes Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(irate(toolchain_storage_bytes_read_total{job=\"remoting-storage-server\", driver=~\".*redis.*\"}[$__interval])) by (driver)",
     "legendFormat": "Read Throughput: {{driver}}"
    },
    {
     "expr": "sum(irate(toolchain_storage_bytes_written_total{job=\"remoting-storage-server\", driver=~\".*redis.*\"}[$__interval])) by (driver)",
     "legendFormat": "Write Throughput: {{driver}}"
    }
   ]
  },
  { "title": "Operation: $operation", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 }, "repeat": "operation" },
  {
   "title": "Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(irate(toolchain_storage_requests_handled_total{job=\"remoting-storage-server\", operation=\"$operation\"}[$__interval]))",
     "legendFormat": "Requests"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.25, sum by (le) (irate(toolchain_storage_requests_handling_seconds_bucket{job=\"remoting-storage-server\", operation=\"$operation\"}[$__interval])))",
     "legendFormat": "P25"
    },
    {
     "expr": "histogram_quantile(0.50, sum by (le) (irate(toolchain_storage_requests_handling_seconds_bucket{job=\"remoting-storage-server\", operation=\"$operation\"}[$__interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (irate(toolchain_storage_requests_handling_seconds_bucket{job=\"remoting-storage-server\", operation=\"$operation\"}[$__interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (irate(toolchain_storage_requests_handling_seconds_bucket{job=\"remoting-storage-server\", operation=\"$operation\"}[$__interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (irate(toolchain_storage_requests_handling_seconds_bucket{job=\"remoting-storage-server\", operation=\"$operation\"}[$__interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (irate(toolchain_storage_requests_handling_seconds_bucket{job=\"remoting-storage-server\", operation=\"$operation\"}[$__interval])))",
     "legendFormat": "P99"
    }
   ]
  }
 ]
}