{
 "title": "Remote Cache and Execution",
 "description": "Graphs of remote caching and execution",
 "tags": [
  "Toolchain",
  "Remoting"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "loadbalancer",
    "query": "app/k8s-prod-prodremo-38c499728f/42c98ceb5ea063ac"
   },
   {
    "name": "namespace",
    "query": {
     "query": "label_values(grpc_server_handled_total, namespace)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Pants Client - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Average cache hit rate (test, CI)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "query": "q = (bucket) =>\n  from(bucket: bucket)\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r._measurement == \"indicators\" and r._field == \"hit_fraction_remote\" and r.goals == \"test\")\n  |> filter(fn: (r) => contains(value: r.context, set: [\"ci_branch\", \"ci_pull_request\"]))\n  |> keep(columns: [\"_time\", \"_value\"])\n\nunion(tables: [q(bucket: \"pantsbuild/pants\"), q(bucket: \"toolchainlabs/toolchain\"), q(bucket: \"color/color\")])\n  |> aggregateWindow(every: duration(v: 10 * int(v: v.windowPeriod)), fn: mean, createEmpty: false)"
    }
   ]
  },
  { "title": "Load Balancer (ALB) - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "ALB Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ALB Non-200 Status",
   "type": "timeseries",
   "description": "NB: 4XXs caused by cancellation are harmless. See https://github.com/toolchainlabs/toolchain/issues/9889",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "ALB Response Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p99"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p50"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p75"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "p90"
    },
    {
     "dimensions": { "LoadBalancer": "$loadbalancer" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Maximum"
    }
   ]
  },
  {
   "title": "Load Balancer (ALB) - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "ALB Connections",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "ActiveConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "NewConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "RejectedConnectionCount",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "ALB Target Status Codes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "HTTPCode_Target_2XX_Count",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "HTTPCode_Target_3XX_Count",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "HTTPCode_Target_4XX_Count",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      },
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "HTTPCode_Target_5XX_Count",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "ALB Usage (LCUs)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "ConsumedLCUs",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "ALB Bytes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "dimensions": { "LoadBalancer": "$loadbalancer" },
       "metricName": "ProcessedBytes",
       "namespace": "AWS/ApplicationELB",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    }
   ]
  },
  { "title": "Proxy - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 } },
  {
   "title": "Proxy Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Proxy Errors (by Type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\", job=\"remoting-proxy-server\", grpc_code!~\"OK|NotFound\"}[$__interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Proxy (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Proxy In-flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
   "targets": [
    {
     "expr": "sum(toolchain_grpc_inflight_requests{namespace=\"$namespace\", job=\"remoting-proxy-server\"})"
    }
   ]
  },
  {
   "title": "Proxy - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Proxy Outbound Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_client_handled_total{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])) by (grpc_service, grpc_method)",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Proxy Errors by Type",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\", job=\"remoting-proxy-server\", grpc_code!~\"OK|NotFound\", grpc_service=~\".*(ActionCache|ByteStream|ContentAddressableStorage)$\"}[$__interval])) by (grpc_code)",
       "legendFormat": "{{grpc_code}}"
      }
     ]
    },
    {
     "title": "Proxy Requests by RPC",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])) by (grpc_service, grpc_method)",
       "legendFormat": "{{grpc_service}}.{{grpc_method}}"
      }
     ]
    },
    {
     "title": "Proxy Requests by Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 53 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Queueing to Storage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
     "targets": [
      {
       "expr": "sum(increase(grpc_client_started_total{job=\"remoting-proxy-server\"}[$__interval])) - sum(increase(grpc_client_handled_total{job=\"remoting-proxy-server\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Tower \"Buffer\" Acqusition Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (increase(toolchain_tower_buffer_acquisition_time_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (increase(toolchain_tower_buffer_acquisition_time_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (increase(toolchain_tower_buffer_acquisition_time_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Tower \"Balance\" Acqusition Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 69 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (increase(toolchain_tower_balance_acquisition_time_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (increase(toolchain_tower_balance_acquisition_time_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (increase(toolchain_tower_balance_acquisition_time_seconds_bucket{namespace=\"$namespace\", job=\"remoting-proxy-server\"}[$__interval])))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Proxy Backend TImeouts",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 69 },
     "targets": [
      {
       "expr": "sum(increase(toolchain_proxy_backend_requests_timed_out_total{namespace=\"$namespace\"}[$__interval])) by (grpc_method)",
       "legendFormat": "{{grpc_method}}"
      }
     ]
    }
   ]
  },
  { "title": "Execution", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 } },
  {
   "title": "Worker state by customer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
   "targets": [
    {
     "expr": "sum by(customer_id, bucket) (toolchain_execution_workers_state{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Job state by customer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
   "targets": [
    {
     "expr": "sum by(customer_id, bucket) (toolchain_execution_actions_state{namespace=\"$namespace\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execute method time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(toolchain_execution_actions_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by(le) (rate(toolchain_execution_actions_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by(le) (rate(toolchain_execution_actions_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by(le) (rate(toolchain_execution_actions_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.99, sum by(le) (rate(toolchain_execution_actions_duration_seconds_bucket{namespace=\"$namespace\"}[$__rate_interval])))",
     "legendFormat": "p99"
    }
   ]
  },
  { "title": "Storage - Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Storage Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])) by (pod)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Storage Errors (by Type)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(grpc_server_handled_total{namespace=\"$namespace\", job=\"remoting-storage-server\", grpc_code!~\"OK|NotFound\"}[$__interval])) by (grpc_code)",
     "legendFormat": "{{grpc_code}}"
    }
   ]
  },
  {
   "title": "Storage (Latency)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P50"
    },
    {
     "expr": "histogram_quantile(0.75, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P75"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P90"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "P95"
    },
    {
     "expr": "histogram_quantile(1, sum by (le) (increase(grpc_server_handling_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
     "legendFormat": "Max"
    }
   ]
  },
  {
   "title": "Storage In-flight Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "sum(toolchain_grpc_inflight_requests{namespace=\"$namespace\", job=\"remoting-storage-server\"})"
    }
   ]
  },
  {
   "title": "Storage Usage by Customer - EFS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(toolchain_remote_cache_usage_bytes{storage_type=\"efs\"}) by (customer)",
     "legendFormat": "{{customer}} - {{storage_type}}"
    }
   ]
  },
  {
   "title": "Storage Usage by Customer - redis",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(toolchain_remote_cache_usage_bytes{storage_type=\"redis\"}) by (customer, storage_type)",
     "legendFormat": "{{customer}} - {{storage_type}}"
    }
   ]
  },
  {
   "title": "Storage - Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 },
   "collapsed": true,
   "panels": [
    {
     "title": "Storage Requests by Operation",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_requests_handled_total{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])) by (operation)",
       "legendFormat": "{{operation}}"
      }
     ]
    },
    {
     "title": "Reads - Time to First Byte",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (increase(toolchain_storage_time_to_first_byte_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (increase(toolchain_storage_time_to_first_byte_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (increase(toolchain_storage_time_to_first_byte_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(toolchain_storage_time_to_first_byte_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (increase(toolchain_storage_time_to_first_byte_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Redis Requests",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_redis_requests_total{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Redis Driver by API",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 79 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_find_missing_blobs_total{namespace=\"$namespace\", job=\"remoting-storage-server\", driver=\"redis\"}[$__interval]))  ",
       "legendFormat": "find missing blobs"
      },
      {
       "expr": "sum(increase(toolchain_storage_blobs_read_total{namespace=\"$namespace\", job=\"remoting-storage-server\", driver=\"redis\"}[$__interval]))  ",
       "legendFormat": "reads"
      },
      {
       "expr": "sum(increase(toolchain_storage_blobs_written_total{namespace=\"$namespace\", job=\"remoting-storage-server\", driver=\"redis\"}[$__interval]))",
       "legendFormat": "writes"
      }
     ]
    },
    {
     "title": "Redis Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.50, sum by (le) (increase(toolchain_storage_redis_requests_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (increase(toolchain_storage_redis_requests_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (increase(toolchain_storage_redis_requests_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(toolchain_storage_redis_requests_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (increase(toolchain_storage_redis_requests_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "Redis Connection Pool Get Delay",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 87 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(0.95, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P95"
      },
      {
       "expr": "histogram_quantile(1, sum by (le) (increase(toolchain_storage_redis_get_connection_duration_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "Max"
      }
     ]
    },
    {
     "title": "AC Completeness",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 95 },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_get_action_result_is_complete{complete=\"false\", service=\"remoting-storage-server\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Incomplete"
      },
      {
       "expr": "sum(increase(toolchain_storage_get_action_result_is_complete{complete=\"true\", service=\"remoting-storage-server\", namespace=\"$namespace\"}[$__interval]))",
       "legendFormat": "Complete"
      }
     ]
    },
    {
     "title": "Redis Connection Pool Errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 95 },
     "targets": [
      {
       "expr": "sum(increase(toolchain_storage_redis_get_connection_duration_seconds_count{namespace=\"$namespace\", job=\"remoting-storage-server\", result=\"error\"}[$__interval]))"
      }
     ]
    },
    {
     "title": "Completion Checking Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.25, sum by (le) (increase(toolchain_storage_completeness_check_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P25"
      },
      {
       "expr": "histogram_quantile(0.50, sum by (le) (increase(toolchain_storage_completeness_check_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P50"
      },
      {
       "expr": "histogram_quantile(0.75, sum by (le) (increase(toolchain_storage_completeness_check_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P75"
      },
      {
       "expr": "histogram_quantile(0.90, sum by (le) (increase(toolchain_storage_completeness_check_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "P90"
      },
      {
       "expr": "histogram_quantile(1.0, sum by (le) (increase(toolchain_storage_completeness_check_seconds_bucket{namespace=\"$namespace\", job=\"remoting-storage-server\"}[$__interval])))",
       "legendFormat": "Max"
      }
     ]
    }
   ]
  },
  {
   "title": "Redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 88 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU Utilization",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "metricName": "EngineCPUUtilization", "namespace": "AWS/ElastiCache", "region": "default", "statistic": "Sum" }
     ]
    },
    {
     "title": "Evictions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "*" },
       "metricName": "Evictions",
       "namespace": "AWS/ElastiCache",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    },
    {
     "title": "Memory Usage Percentage",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "*" },
       "metricName": "DatabaseMemoryUsagePercentage",
       "namespace": "AWS/ElastiCache",
       "region": "default",
       "statistic": "Average"
      }
     ]
    },
    {
     "title": "Replication Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "dimensions": { "CacheClusterId": "remoting-storage-rg-1-002" },
       "metricName": "ReplicationLag",
       "namespace": "AWS/ElastiCache",
       "region": "default",
       "statistic": "Sum"
      }
     ]
    }
   ]
  }
 ]
}