# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

python_tests(
    name="tests",
    dependencies=[
        "3rdparty/python#Django",  # Test time dependency since we use Sentry's Django Integration
    ],
)
