# Copyright 2017 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

pex_binary(
    name="generate_service_boilerplate",
    entry_point="generate_service_boilerplate.py",
)
