# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources(
    overrides={
        ("multipart_parser.py", "util.py"): {"resolve": parametrize("pants-plugin", "default-toolchain")},
    },
)
