# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

python_tests(
    name="tests",
    dependencies=[
        "!src/python/toolchain/bitbucket_integration/conftest.py:test_utils",
        "!src/python/toolchain/conftest.py:test_utils",
    ],
)
