# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.11 on 2022-01-06 23:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("workflow", "0007_auto_20210315_1519"),
    ]

    operations = [
        migrations.CreateModel(
            name="DownloadBugoutDataForDay",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("day", models.DateField(editable=False, unique=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ScheduleBugoutDataDownload",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.workunit",
                    ),
                ),
                ("period_minutes", models.IntegerField(null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
