# Copyright 2022 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.2.11 on 2022-01-24 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bugout_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="downloadbugoutdataforday",
            name="journal_id",
            field=models.CharField(default="", editable=False, max_length=36),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedulebugoutdatadownload",
            name="journal_id",
            field=models.CharField(default="", editable=False, max_length=36, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="downloadbugoutdataforday",
            name="day",
            field=models.DateField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name="downloadbugoutdataforday",
            unique_together={("day", "journal_id")},
        ),
    ]
