# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.1 on 2019-06-05 21:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("workflow", "0001_initial"), ("webresource", "0001_initial"), ("packagerepomaven", "0001_initial")]

    operations = [
        migrations.CreateModel(
            name="ProcessMavenMetadata",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                (
                    "web_resource",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="webresource.WebResource"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ProcessLinkPage",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                (
                    "web_resource",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="webresource.WebResource"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="LocateParentPOM",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                (
                    "web_resource",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="webresource.WebResource"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="IndexLatestVersionOfMavenArtifact",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("kind", models.CharField(choices=[("BIN", "lib-binary-jar"), ("SRC", "lib")], max_length=3)),
                (
                    "artifact",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packagerepomaven.MavenArtifact"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ExtractPOMInfo",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                (
                    "web_resource",
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to="webresource.WebResource"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="MavenArtifactKytheEntries",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("location", models.URLField(db_index=True, max_length=500, unique=True)),
                (
                    "compression",
                    models.CharField(
                        choices=[
                            ("UNCOMPRESSED", "uncompressed"),
                            ("TAR", ".tar"),
                            ("ZIP", ".zip"),
                            ("GZTAR", ".tar.gz"),
                            ("BZTAR", ".tar.bz"),
                        ],
                        max_length=12,
                    ),
                ),
                ("version", models.CharField(max_length=150)),
                ("kind", models.CharField(choices=[("BIN", "lib-binary-jar"), ("SRC", "lib")], max_length=3)),
                (
                    "artifact",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packagerepomaven.MavenArtifact"),
                ),
            ],
            options={"unique_together": {("artifact", "version", "kind")}},
        ),
        migrations.CreateModel(
            name="IndexMavenArtifact",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("version", models.CharField(max_length=150)),
                ("corpus", models.CharField(max_length=500)),
                ("kind", models.CharField(choices=[("BIN", "lib-binary-jar"), ("SRC", "lib")], max_length=3)),
                (
                    "artifact",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packagerepomaven.MavenArtifact"),
                ),
            ],
            options={"unique_together": {("artifact", "version", "corpus", "kind")}},
        ),
    ]
