# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-15 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("workflow", "0004_auto_20190913_2212")]

    operations = [
        migrations.CreateModel(
            name="DumpDistributionData",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("shard", models.IntegerField()),
                ("num_shards", models.IntegerField(choices=[(16, "num"), (256, "num")])),
                ("bucket", models.CharField(max_length=64)),
                ("key_prefix", models.CharField(max_length=512)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ProcessAllProjects",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("created_at", models.DateTimeField(db_index=True)),
                ("serial", models.IntegerField()),
                ("num_shards", models.IntegerField()),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ProcessAllProjectsShard",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("shard_number", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ProcessDistribution",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                )
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ProcessProject",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("project_name", models.CharField(db_index=True, max_length=100)),
                ("required_serial", models.IntegerField()),
                ("num_distributions", models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProcessProjectDistribution",
            fields=[("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID"))],
            options={"abstract": False},
        ),
    ]
