# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-15 22:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [("packagerepopypi", "0001_initial"), ("crawlerpypi", "0001_initial")]

    operations = [
        migrations.AddField(
            model_name="processprojectdistribution",
            name="distribution",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packagerepopypi.Distribution"),
        ),
        migrations.AddField(
            model_name="processprojectdistribution",
            name="process_project",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crawlerpypi.ProcessProject"),
        ),
        migrations.AddField(
            model_name="processproject",
            name="distributions",
            field=models.ManyToManyField(
                related_name="process_projects",
                through="crawlerpypi.ProcessProjectDistribution",
                to="packagerepopypi.Distribution",
            ),
        ),
        migrations.AddField(
            model_name="processproject",
            name="shard",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.CASCADE, to="crawlerpypi.ProcessAllProjectsShard"
            ),
        ),
        migrations.AddField(
            model_name="processdistribution",
            name="distribution",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packagerepopypi.Distribution"),
        ),
        migrations.AddField(
            model_name="processallprojectsshard",
            name="process_all_projects",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="shards", to="crawlerpypi.ProcessAllProjects"
            ),
        ),
        migrations.AlterUniqueTogether(name="processproject", unique_together={("shard", "project_name")}),
        migrations.AlterUniqueTogether(
            name="processallprojectsshard", unique_together={("process_all_projects", "shard_number")}
        ),
    ]
