# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-16 01:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("workflow", "0004_auto_20190913_2212"), ("crawlerpypi", "0002_auto_20190915_2231")]

    operations = [
        migrations.CreateModel(
            name="ProcessChangelog",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("serial_from", models.IntegerField()),
                ("serial_to", models.IntegerField()),
                ("num_distributions_added", models.IntegerField(null=True)),
                ("num_distributions_removed", models.IntegerField(null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.AlterField(
            model_name="processproject",
            name="shard",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="process_projects",
                to="crawlerpypi.ProcessAllProjectsShard",
            ),
        ),
    ]
