# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-17 17:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workflow", "0004_auto_20190913_2212"),
        ("packagerepopypi", "0001_initial"),
        ("crawlerpypi", "0003_auto_20190916_0138"),
    ]

    operations = [
        migrations.CreateModel(
            name="PeriodicallyProcessChangelog",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("period_minutes", models.IntegerField(null=True)),
            ],
            options={"abstract": False},
        ),
        migrations.AlterField(model_name="processallprojects", name="serial", field=models.IntegerField(db_index=True)),
        migrations.AlterField(
            model_name="processchangelog", name="serial_from", field=models.IntegerField(db_index=True)
        ),
        migrations.AlterField(
            model_name="processchangelog", name="serial_to", field=models.IntegerField(db_index=True)
        ),
        migrations.AlterField(
            model_name="processproject",
            name="distributions",
            field=models.ManyToManyField(
                related_name="processed_by",
                through="crawlerpypi.ProcessProjectDistribution",
                to="packagerepopypi.Distribution",
            ),
        ),
        migrations.CreateModel(
            name="ProcessChangelogRemoved",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "distribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packagerepopypi.Distribution"),
                ),
                (
                    "process_changelog",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crawlerpypi.ProcessChangelog"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="ProcessChangelogAdded",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "distribution",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="packagerepopypi.Distribution"),
                ),
                (
                    "process_changelog",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="crawlerpypi.ProcessChangelog"),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AddField(
            model_name="processchangelog",
            name="distributions_added",
            field=models.ManyToManyField(
                related_name="added_by", through="crawlerpypi.ProcessChangelogAdded", to="packagerepopypi.Distribution"
            ),
        ),
        migrations.AddField(
            model_name="processchangelog",
            name="distributions_removed",
            field=models.ManyToManyField(
                related_name="removed_by",
                through="crawlerpypi.ProcessChangelogRemoved",
                to="packagerepopypi.Distribution",
            ),
        ),
    ]
