# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("workflow", "0004_auto_20190913_2212"), ("crawlerpypi", "0004_auto_20190917_1709")]

    operations = [
        migrations.AddField(
            model_name="dumpdistributiondata",
            name="serial_from",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dumpdistributiondata",
            name="serial_to",
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
