# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.4 on 2019-09-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crawlerpypi", "0005_auto_20190918_1615")]

    operations = [
        migrations.AlterField(
            model_name="dumpdistributiondata", name="serial_from", field=models.IntegerField(db_index=True)
        ),
        migrations.AlterField(
            model_name="dumpdistributiondata", name="serial_to", field=models.IntegerField(db_index=True)
        ),
    ]
