# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.5 on 2019-09-19 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("workflow", "0004_auto_20190913_2212"), ("crawlerpypi", "0006_auto_20190918_1856")]

    operations = [
        migrations.CreateModel(
            name="PeriodicallyUpdateLevelDb",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("period_minutes", models.IntegerField(null=True)),
                ("input_dir_url", models.URLField(max_length=500)),
                ("output_dir_url", models.URLField(max_length=500)),
                ("builder_cls", models.CharField(max_length=100)),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="UpdateLevelDb",
            fields=[
                (
                    "work_unit",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        related_name="+",
                        serialize=False,
                        to="workflow.WorkUnit",
                    ),
                ),
                ("input_dir_url", models.URLField(max_length=500)),
                ("output_dir_url", models.URLField(max_length=500)),
                ("builder_cls", models.CharField(max_length=100)),
            ],
            options={"abstract": False},
        ),
        migrations.AlterField(
            model_name="dumpdistributiondata",
            name="num_shards",
            field=models.IntegerField(choices=[(1, "num"), (16, "num"), (256, "num")]),
        ),
    ]
