# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.5 on 2019-09-20 17:34
# flake8: noqa: DJ01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crawlerpypi", "0007_auto_20190919_1656")]

    operations = [
        migrations.RenameField(
            model_name="periodicallyupdateleveldb", old_name="output_dir_url", new_name="output_dir_base_url"
        ),
        migrations.AddField(
            model_name="updateleveldb",
            name="existing_leveldb_dir_url",
            field=models.URLField(max_length=500, null=True),
        ),
    ]
