# Copyright 2019 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 2.2.5 on 2019-10-15 23:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [("crawlerpypi", "0008_auto_20190920_1734")]

    operations = [
        migrations.AlterUniqueTogether(name="processproject", unique_together=set()),
        migrations.RemoveField(model_name="processproject", name="shard"),
    ]
