# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.2 on 2020-01-24 02:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("crawlerpypi", "0009_auto_20191015_2338")]

    operations = [
        migrations.AlterField(
            model_name="updateleveldb",
            name="existing_leveldb_dir_url",
            field=models.URLField(default="", max_length=500),
        )
    ]
