# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.0.5 on 2020-04-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawlerpypi", "0010_auto_20200124_0233"),
    ]

    operations = [
        migrations.AddField(
            model_name="periodicallyupdateleveldb", name="rebuild", field=models.BooleanField(default=False)
        )
    ]
