# Copyright 2021 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

# Generated by Django 3.1.7 on 2021-03-15 15:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("crawlerpypi", "0011_periodicallyupdateleveldb_rebuild"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processchangelogadded",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="processprojectdistribution",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
