# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()

pex_binary(
    name="aws_cost_reporter_tool",
    entry_point="notify_costs_tool.py",
)
