# Copyright 2020 Toolchain Labs, Inc. All rights reserved.
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_sources()


pex_binary(
    name="db_creds_rotator",
    entry_point="credentials_rotator.py",
)
